package jp.co.vermore.jsonparse;

import jp.co.vermore.common.mvc.BaseEntity;

import java.util.Date;

public class PurchaseInfoJsonParse {

    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_info.first_name1
     *
     * @mbggenerated Wed May 02 17:25:39 CST 2018
     */
    private String firstName1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_info.last_name1
     *
     * @mbggenerated Wed May 02 17:25:39 CST 2018
     */
    private String lastName1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_info.first_name2
     *
     * @mbggenerated Wed May 02 17:25:39 CST 2018
     */
    private String firstName2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_info.last_name2
     *
     * @mbggenerated Wed May 02 17:25:39 CST 2018
     */
    private String lastName2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_info.zip_code
     *
     * @mbggenerated Wed May 02 17:25:39 CST 2018
     */
    private String zipCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_info.address1
     *
     * @mbggenerated Wed May 02 17:25:39 CST 2018
     */
    private String address1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_info.address2
     *
     * @mbggenerated Wed May 02 17:25:39 CST 2018
     */
    private String address2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_info.email
     *
     * @mbggenerated Wed May 02 17:25:39 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_info.tel
     *
     * @mbggenerated Wed May 02 17:25:39 CST 2018
     */
    private String tel;


    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_info.user_id
     *
     * @param userId the value for purchase_info.user_id
     *
     * @mbggenerated Wed May 02 17:25:39 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_info.first_name1
     *
     * @return the value of purchase_info.first_name1
     *
     * @mbggenerated Wed May 02 17:25:39 CST 2018
     */
    public String getFirstName1() {
        return firstName1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_info.first_name1
     *
     * @param firstName1 the value for purchase_info.first_name1
     *
     * @mbggenerated Wed May 02 17:25:39 CST 2018
     */
    public void setFirstName1(String firstName1) {
        this.firstName1 = firstName1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_info.last_name1
     *
     * @return the value of purchase_info.last_name1
     *
     * @mbggenerated Wed May 02 17:25:39 CST 2018
     */
    public String getLastName1() {
        return lastName1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_info.last_name1
     *
     * @param lastName1 the value for purchase_info.last_name1
     *
     * @mbggenerated Wed May 02 17:25:39 CST 2018
     */
    public void setLastName1(String lastName1) {
        this.lastName1 = lastName1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_info.first_name2
     *
     * @return the value of purchase_info.first_name2
     *
     * @mbggenerated Wed May 02 17:25:39 CST 2018
     */
    public String getFirstName2() {
        return firstName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_info.first_name2
     *
     * @param firstName2 the value for purchase_info.first_name2
     *
     * @mbggenerated Wed May 02 17:25:39 CST 2018
     */
    public void setFirstName2(String firstName2) {
        this.firstName2 = firstName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_info.last_name2
     *
     * @return the value of purchase_info.last_name2
     *
     * @mbggenerated Wed May 02 17:25:39 CST 2018
     */
    public String getLastName2() {
        return lastName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_info.last_name2
     *
     * @param lastName2 the value for purchase_info.last_name2
     *
     * @mbggenerated Wed May 02 17:25:39 CST 2018
     */
    public void setLastName2(String lastName2) {
        this.lastName2 = lastName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_info.zip_code
     *
     * @return the value of purchase_info.zip_code
     *
     * @mbggenerated Wed May 02 17:25:39 CST 2018
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_info.zip_code
     *
     * @param zipCode the value for purchase_info.zip_code
     *
     * @mbggenerated Wed May 02 17:25:39 CST 2018
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_info.address1
     *
     * @return the value of purchase_info.address1
     *
     * @mbggenerated Wed May 02 17:25:39 CST 2018
     */
    public String getAddress1() {
        return address1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_info.address1
     *
     * @param address1 the value for purchase_info.address1
     *
     * @mbggenerated Wed May 02 17:25:39 CST 2018
     */
    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_info.address2
     *
     * @return the value of purchase_info.address2
     *
     * @mbggenerated Wed May 02 17:25:39 CST 2018
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_info.address2
     *
     * @param address2 the value for purchase_info.address2
     *
     * @mbggenerated Wed May 02 17:25:39 CST 2018
     */
    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_info.email
     *
     * @return the value of purchase_info.email
     *
     * @mbggenerated Wed May 02 17:25:39 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_info.email
     *
     * @param email the value for purchase_info.email
     *
     * @mbggenerated Wed May 02 17:25:39 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_info.tel
     *
     * @return the value of purchase_info.tel
     *
     * @mbggenerated Wed May 02 17:25:39 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_info.tel
     *
     * @param tel the value for purchase_info.tel
     *
     * @mbggenerated Wed May 02 17:25:39 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel;
    }


}