package jp.co.vermore.jsonparse;

import java.util.List;

import jp.co.vermore.entity.Comment;
import jp.co.vermore.common.mvc.BaseJsonParse;

public class RiseDetailJsonParse extends BaseJsonParse {

    private String name1;

    private String name2;

    private String office;

    private String honor;

    private String category;

    private String topTitle;

    private String title1;

    private String title2;

    private String title3;

    private String topPicUrl;

    private String picUrl1;

    private String picUrl2;

    private String picUrl3;

    private String picUrl4;

    private String videoUrl1;

    private String desc1;

    private String desc2;

    private String desc3;

    private List<Comment> comment;

    public String getName1() {
        return name1;
    }

    public void setName1(String name1) {
        this.name1 = name1;
    }

    public String getName2() {
        return name2;
    }

    public void setName2(String name2) {
        this.name2 = name2;
    }

    public String getOffice() {
        return office;
    }

    public void setOffice(String office) {
        this.office = office;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rise_detail.honor
     *
     * @return the value of rise_detail.honor
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public String getHonor() {
        return honor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rise_detail.honor
     *
     * @param honor the value for rise_detail.honor
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setHonor(String honor) {
        this.honor = honor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rise_detail.category
     *
     * @return the value of rise_detail.category
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rise_detail.category
     *
     * @param category the value for rise_detail.category
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rise_detail.top_title
     *
     * @return the value of rise_detail.top_title
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public String getTopTitle() {
        return topTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rise_detail.top_title
     *
     * @param topTitle the value for rise_detail.top_title
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setTopTitle(String topTitle) {
        this.topTitle = topTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rise_detail.title1
     *
     * @return the value of rise_detail.title1
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public String getTitle1() {
        return title1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rise_detail.title1
     *
     * @param title1 the value for rise_detail.title1
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setTitle1(String title1) {
        this.title1 = title1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rise_detail.title2
     *
     * @return the value of rise_detail.title2
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public String getTitle2() {
        return title2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rise_detail.title2
     *
     * @param title2 the value for rise_detail.title2
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setTitle2(String title2) {
        this.title2 = title2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rise_detail.title3
     *
     * @return the value of rise_detail.title3
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public String getTitle3() {
        return title3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rise_detail.title3
     *
     * @param title3 the value for rise_detail.title3
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setTitle3(String title3) {
        this.title3 = title3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rise_detail.birthday
     *
     * @return the value of rise_detail.birthday
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */




    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rise_detail.top_pic_url
     *
     * @return the value of rise_detail.top_pic_url
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public String getTopPicUrl() {
        return topPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rise_detail.top_pic_url
     *
     * @param topPicUrl the value for rise_detail.top_pic_url
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setTopPicUrl(String topPicUrl) {
        this.topPicUrl = topPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rise_detail.pic_url1
     *
     * @return the value of rise_detail.pic_url1
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public String getPicUrl1() {
        return picUrl1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rise_detail.pic_url1
     *
     * @param picUrl1 the value for rise_detail.pic_url1
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setPicUrl1(String picUrl1) {
        this.picUrl1 = picUrl1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rise_detail.pic_url2
     *
     * @return the value of rise_detail.pic_url2
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public String getPicUrl2() {
        return picUrl2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rise_detail.pic_url2
     *
     * @param picUrl2 the value for rise_detail.pic_url2
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setPicUrl2(String picUrl2) {
        this.picUrl2 = picUrl2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rise_detail.pic_url3
     *
     * @return the value of rise_detail.pic_url3
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public String getPicUrl3() {
        return picUrl3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rise_detail.pic_url3
     *
     * @param picUrl3 the value for rise_detail.pic_url3
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setPicUrl3(String picUrl3) {
        this.picUrl3 = picUrl3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rise_detail.pic_url4
     *
     * @return the value of rise_detail.pic_url4
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public String getPicUrl4() {
        return picUrl4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rise_detail.pic_url4
     *
     * @param picUrl4 the value for rise_detail.pic_url4
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setPicUrl4(String picUrl4) {
        this.picUrl4 = picUrl4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rise_detail.video_url1
     *
     * @return the value of rise_detail.video_url1
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public String getVideoUrl1() {
        return videoUrl1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rise_detail.video_url1
     *
     * @param videoUrl1 the value for rise_detail.video_url1
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setVideoUrl1(String videoUrl1) {
        this.videoUrl1 = videoUrl1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rise_detail.desc1
     *
     * @return the value of rise_detail.desc1
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public String getDesc1() {
        return desc1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rise_detail.desc1
     *
     * @param desc1 the value for rise_detail.desc1
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setDesc1(String desc1) {
        this.desc1 = desc1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rise_detail.desc2
     *
     * @return the value of rise_detail.desc2
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public String getDesc2() {
        return desc2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rise_detail.desc2
     *
     * @param desc2 the value for rise_detail.desc2
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setDesc2(String desc2) {
        this.desc2 = desc2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rise_detail.desc3
     *
     * @return the value of rise_detail.desc3
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public String getDesc3() {
        return desc3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rise_detail.desc3
     *
     * @param desc3 the value for rise_detail.desc3
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setDesc3(String desc3) {
        this.desc3 = desc3;
    }

    public List<Comment> getComment() {
        return comment;
    }

    public void setComment(List<Comment> comment) {
        this.comment = comment;
    }
}