package jp.co.vermore.mapper;

import jp.co.vermore.entity.AdminPermission;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AdminPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permission
     *
     * @mbggenerated Mon Mar 26 13:14:10 CST 2018
     */
    int countByExample(AdminPermission adminPermission);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permission
     *
     * @mbggenerated Mon Mar 26 13:14:10 CST 2018
     */
    int deleteByExample(AdminPermission adminPermission);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permission
     *
     * @mbggenerated Mon Mar 26 13:14:10 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permission
     *
     * @mbggenerated Mon Mar 26 13:14:10 CST 2018
     */
    int insert(AdminPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permission
     *
     * @mbggenerated Mon Mar 26 13:14:10 CST 2018
     */
    int insertSelective(AdminPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permission
     *
     * @mbggenerated Mon Mar 26 13:14:10 CST 2018
     */
    List<AdminPermission> selectByExample(AdminPermission adminPermission);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permission
     *
     * @mbggenerated Mon Mar 26 13:14:10 CST 2018
     */
    AdminPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permission
     *
     * @mbggenerated Mon Mar 26 13:14:10 CST 2018
     */
    int updateByExampleSelective(@Param("record") AdminPermission record, @Param("example") AdminPermission adminPermission);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permission
     *
     * @mbggenerated Mon Mar 26 13:14:10 CST 2018
     */
    int updateByExample(@Param("record") AdminPermission record, @Param("example") AdminPermission adminPermission);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permission
     *
     * @mbggenerated Mon Mar 26 13:14:10 CST 2018
     */
    int updateByPrimaryKeySelective(AdminPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permission
     *
     * @mbggenerated Mon Mar 26 13:14:10 CST 2018
     */
    int updateByPrimaryKey(AdminPermission record);
}