package jp.co.vermore.mapper;

import jp.co.vermore.entity.AdminRole;
import jp.co.vermore.entity.AdminRoleExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AdminRoleMapper {

  int insertAdminRole(AdminRole role);

  int updateAdminRole(AdminRole role);



  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table admin_role
   *
   * @mbggenerated
   */
  List<AdminRole> selectByExample(AdminRoleExample example);

  AdminRole selectById(Long id);
}