package jp.co.vermore.mapper;

import jp.co.vermore.entity.EventDetail;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EventDetailMapper {

    EventDetail selectByEventId(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_detail
     *
     * @mbggenerated Mon Apr 16 16:47:42 JST 2018
     */
    int countByExample(EventDetail eventDetail);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_detail
     *
     * @mbggenerated Mon Apr 16 16:47:42 JST 2018
     */
    int deleteByExample(EventDetail eventDetail);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_detail
     *
     * @mbggenerated Mon Apr 16 16:47:42 JST 2018
     */
    Long deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_detail
     *
     * @mbggenerated Mon Apr 16 16:47:42 JST 2018
     */
    Long insert(EventDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_detail
     *
     * @mbggenerated Mon Apr 16 16:47:42 JST 2018
     */
    int insertSelective(EventDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_detail
     *
     * @mbggenerated Mon Apr 16 16:47:42 JST 2018
     */
    List<EventDetail> selectByExample(EventDetail eventDetail);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_detail
     *
     * @mbggenerated Mon Apr 16 16:47:42 JST 2018
     */
    EventDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_detail
     *
     * @mbggenerated Mon Apr 16 16:47:42 JST 2018
     */
    int updateByExampleSelective(@Param("record") EventDetail record, @Param("example") EventDetail eventDetail);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_detail
     *
     * @mbggenerated Mon Apr 16 16:47:42 JST 2018
     */
    int updateByExample(@Param("record") EventDetail record, @Param("example") EventDetail eventDetail);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_detail
     *
     * @mbggenerated Mon Apr 16 16:47:42 JST 2018
     */
    Long updateByPrimaryKeySelective(EventDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_detail
     *
     * @mbggenerated Mon Apr 16 16:47:42 JST 2018
     */
    int updateByPrimaryKey(EventDetail record);
}