package jp.co.vermore.mapper;

import java.util.Date;
import java.util.List;

import jp.co.vermore.entity.Event;
import jp.co.vermore.form.admin.DatatablesBaseForm;
import jp.co.vermore.form.admin.EventListForm;
import org.apache.ibatis.annotations.Param;

public interface EventMapper {

    List<Event> getEventAll(String tomorrow,String today, Long limit, Long offset);

    List<Event> getEventAll1(String tomorrow,String today);

    List<Event> getEvent(String tomorrow,String today);

    List<Event> getEventForTop(String tomorrow,String today);

    Event getEventByUuid(String uuid);

    Event getEventById(Long id);

    Long deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbggenerated Mon Apr 16 16:47:42 JST 2018
     */
    int countByExample(Event event);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbggenerated Mon Apr 16 16:47:42 JST 2018
     */
    int deleteByExample(Event event);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbggenerated Mon Apr 16 16:47:42 JST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbggenerated Mon Apr 16 16:47:42 JST 2018
     */
    int insert(Event record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbggenerated Mon Apr 16 16:47:42 JST 2018
     */
    int insertSelective(Event record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbggenerated Mon Apr 16 16:47:42 JST 2018
     */
    List<Event> selectByExample(Event event);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbggenerated Mon Apr 16 16:47:42 JST 2018
     */
    Event selectByPrimaryKey(long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbggenerated Mon Apr 16 16:47:42 JST 2018
     */
    int updateByExampleSelective(@Param("record") Event record, @Param("example") Event event);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbggenerated Mon Apr 16 16:47:42 JST 2018
     */
    int updateByExample(@Param("record") Event record, @Param("example") Event event);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbggenerated Mon Apr 16 16:47:42 JST 2018
     */
    Long updateByPrimaryKeySelective(Event record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbggenerated Mon Apr 16 16:47:42 JST 2018
     */
    int updateByPrimaryKey(Event record);

    List<Event> getEventAllByCondition(EventListForm form);

    int getEventCountByCondition(EventListForm form);

    int getEventCount();

    Event getEventPre(Date date,String tomorrow,String today);

    Event getEventNext(Date date,String tomorrow,String today);

}