package jp.co.vermore.mapper;

import java.util.List;
import jp.co.vermore.entity.Invite;
import org.apache.ibatis.annotations.Param;

public interface InviteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite
     *
     * @mbggenerated Wed Feb 28 15:54:28 CST 2018
     */
    int countByExample(Invite invite);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite
     *
     * @mbggenerated Wed Feb 28 15:54:28 CST 2018
     */
    int deleteByExample(Invite invite);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite
     *
     * @mbggenerated Wed Feb 28 15:54:28 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite
     *
     * @mbggenerated Wed Feb 28 15:54:28 CST 2018
     */
    int insert(Invite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite
     *
     * @mbggenerated Wed Feb 28 15:54:28 CST 2018
     */
    int insertSelective(Invite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite
     *
     * @mbggenerated Wed Feb 28 15:54:28 CST 2018
     */
    List<Invite> selectByExample(Invite invite);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite
     *
     * @mbggenerated Wed Feb 28 15:54:28 CST 2018
     */
    Invite selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite
     *
     * @mbggenerated Wed Feb 28 15:54:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") Invite record, @Param("example") Invite invite);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite
     *
     * @mbggenerated Wed Feb 28 15:54:28 CST 2018
     */
    int updateByExample(@Param("record") Invite record, @Param("example") Invite invite);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite
     *
     * @mbggenerated Wed Feb 28 15:54:28 CST 2018
     */
    int updateByPrimaryKeySelective(Invite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite
     *
     * @mbggenerated Wed Feb 28 15:54:28 CST 2018
     */
    int updateByPrimaryKey(Invite record);
}