package jp.co.vermore.mapper;

import java.util.List;
import jp.co.vermore.entity.RecruitDetail;
import jp.co.vermore.form.admin.RecruitListForm;
import org.apache.ibatis.annotations.Param;

public interface RecruitDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_detail
     *
     * @mbggenerated Wed Feb 28 15:54:27 CST 2018
     */
    int countByExample(RecruitDetail recruitDetail);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_detail
     *
     * @mbggenerated Wed Feb 28 15:54:27 CST 2018
     */
    int deleteByExample(RecruitDetail recruitDetail);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_detail
     *
     * @mbggenerated Wed Feb 28 15:54:27 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_detail
     *
     * @mbggenerated Wed Feb 28 15:54:27 CST 2018
     */
    int insert(RecruitDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_detail
     *
     * @mbggenerated Wed Feb 28 15:54:27 CST 2018
     */
    long insertSelective(RecruitDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_detail
     *
     * @mbggenerated Wed Feb 28 15:54:27 CST 2018
     */
    List<RecruitDetail> selectByExample(RecruitDetail recruitDetail);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_detail
     *
     * @mbggenerated Wed Feb 28 15:54:27 CST 2018
     */
    RecruitDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_detail
     *
     * @mbggenerated Wed Feb 28 15:54:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") RecruitDetail record, @Param("example") RecruitDetail recruitDetail);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_detail
     *
     * @mbggenerated Wed Feb 28 15:54:27 CST 2018
     */
    int updateByExample(@Param("record") RecruitDetail record, @Param("example") RecruitDetail recruitDetail);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_detail
     *
     * @mbggenerated Wed Feb 28 15:54:27 CST 2018
     */
    int updateByPrimaryKeySelective(RecruitDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_detail
     *
     * @mbggenerated Wed Feb 28 15:54:27 CST 2018
     */
    int updateByPrimaryKey(RecruitDetail record);

    void insertRecruitDetail(RecruitDetail recruitDetail);

    int deleteRecruitDetail(RecruitDetail recruitDetail);

    int updateRecruitDetail(RecruitDetail recruitDetail);

    RecruitDetail getRecruitDetail(int id);

    List<RecruitDetail> getRecruitDetailAll(int id);

    RecruitDetail getRecruitDetailByRecruit(Long id);

    int updateByRecruitSelective(RecruitDetail recruitDetail);

    List<RecruitDetail> getRecruitDetailAllByLimit(int limit, int offset);

    List<RecruitDetail> getRecruitDetailAllByCondition(RecruitListForm form);

    int getRecruitDetailCountByCondition(RecruitListForm form);

    int getRecruitDetailCount();

    int deleteDetailVideo(Long recruitId);



}