package jp.co.vermore.mapper;

import java.util.List;
import jp.co.vermore.entity.SessionId;
import org.apache.ibatis.annotations.Param;

public interface SessionIdMapper {

    SessionId selectByUuidAndSessionId(String uuid, String sessionId);

    SessionId selectBySessionId(String sessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_id
     *
     * @mbggenerated Wed Feb 28 15:54:27 CST 2018
     */
    int countByExample(SessionId sessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_id
     *
     * @mbggenerated Wed Feb 28 15:54:27 CST 2018
     */
    int deleteByExample(SessionId sessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_id
     *
     * @mbggenerated Wed Feb 28 15:54:27 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_id
     *
     * @mbggenerated Wed Feb 28 15:54:27 CST 2018
     */
    int insert(SessionId record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_id
     *
     * @mbggenerated Wed Feb 28 15:54:27 CST 2018
     */
    int insertSelective(SessionId record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_id
     *
     * @mbggenerated Wed Feb 28 15:54:27 CST 2018
     */
    List<SessionId> selectByExample(SessionId sessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_id
     *
     * @mbggenerated Wed Feb 28 15:54:27 CST 2018
     */
    SessionId selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_id
     *
     * @mbggenerated Wed Feb 28 15:54:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") SessionId record, @Param("example") SessionId sessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_id
     *
     * @mbggenerated Wed Feb 28 15:54:27 CST 2018
     */
    int updateByExample(@Param("record") SessionId record, @Param("example") SessionId sessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_id
     *
     * @mbggenerated Wed Feb 28 15:54:27 CST 2018
     */
    int updateByPrimaryKeySelective(SessionId record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_id
     *
     * @mbggenerated Wed Feb 28 15:54:27 CST 2018
     */
    int updateByPrimaryKey(SessionId record);
}