package jp.co.vermore.mapper;

import jp.co.vermore.entity.SettlementMaster;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SettlementMasterMapper {

    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement_master
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    int insert(SettlementMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement_master
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    int insertSelective(SettlementMaster record);

    SettlementMaster selectByPrimaryKey(Integer id);

    int updateByPrimaryKeySelective(SettlementMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement_master
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    int updateByPrimaryKey(SettlementMaster record);
}