package jp.co.vermore.mapper;

import jp.co.vermore.entity.SystemConf;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SystemConfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_conf
     *
     * @mbggenerated Thu Mar 29 16:16:52 JST 2018
     */
    int countByExample(SystemConf example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_conf
     *
     * @mbggenerated Thu Mar 29 16:16:52 JST 2018
     */
    int deleteByExample(SystemConf example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_conf
     *
     * @mbggenerated Thu Mar 29 16:16:52 JST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_conf
     *
     * @mbggenerated Thu Mar 29 16:16:52 JST 2018
     */
    int insert(SystemConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_conf
     *
     * @mbggenerated Thu Mar 29 16:16:52 JST 2018
     */
    int insertSelective(SystemConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_conf
     *
     * @mbggenerated Thu Mar 29 16:16:52 JST 2018
     */
    List<SystemConf> selectByExample(SystemConf example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_conf
     *
     * @mbggenerated Thu Mar 29 16:16:52 JST 2018
     */
    SystemConf selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_conf
     *
     * @mbggenerated Thu Mar 29 16:16:52 JST 2018
     */
    int updateByExampleSelective(@Param("record") SystemConf record, @Param("example") SystemConf example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_conf
     *
     * @mbggenerated Thu Mar 29 16:16:52 JST 2018
     */
    int updateByExample(@Param("record") SystemConf record, @Param("example") SystemConf example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_conf
     *
     * @mbggenerated Thu Mar 29 16:16:52 JST 2018
     */
    int updateByPrimaryKeySelective(SystemConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_conf
     *
     * @mbggenerated Thu Mar 29 16:16:52 JST 2018
     */
    int updateByPrimaryKey(SystemConf record);

    List<SystemConf> selectAll();

    SystemConf getSystemConfByKey(int setting);
}