package jp.co.vermore.entity;

import java.util.Date;

public class AdminUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.id
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.login_name
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.status
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.password
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.show_name
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    private String showName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.mail
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    private String mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.role
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    private Long role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.create_datetime
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.create_user
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.update_datetime
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.update_user
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.del_flg
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    private Boolean delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.note
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.id
     *
     * @return the value of admin_user.id
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.id
     *
     * @param id the value for admin_user.id
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.login_name
     *
     * @return the value of admin_user.login_name
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.login_name
     *
     * @param loginName the value for admin_user.login_name
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.status
     *
     * @return the value of admin_user.status
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.status
     *
     * @param status the value for admin_user.status
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.password
     *
     * @return the value of admin_user.password
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.password
     *
     * @param password the value for admin_user.password
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.show_name
     *
     * @return the value of admin_user.show_name
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    public String getShowName() {
        return showName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.show_name
     *
     * @param showName the value for admin_user.show_name
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    public void setShowName(String showName) {
        this.showName = showName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.mail
     *
     * @return the value of admin_user.mail
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.mail
     *
     * @param mail the value for admin_user.mail
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.role
     *
     * @return the value of admin_user.role
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    public Long getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.role
     *
     * @param role the value for admin_user.role
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    public void setRole(Long role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.create_datetime
     *
     * @return the value of admin_user.create_datetime
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.create_datetime
     *
     * @param createDatetime the value for admin_user.create_datetime
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.create_user
     *
     * @return the value of admin_user.create_user
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.create_user
     *
     * @param createUser the value for admin_user.create_user
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.update_datetime
     *
     * @return the value of admin_user.update_datetime
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.update_datetime
     *
     * @param updateDatetime the value for admin_user.update_datetime
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.update_user
     *
     * @return the value of admin_user.update_user
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.update_user
     *
     * @param updateUser the value for admin_user.update_user
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.del_flg
     *
     * @return the value of admin_user.del_flg
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.del_flg
     *
     * @param delFlg the value for admin_user.del_flg
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.note
     *
     * @return the value of admin_user.note
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.note
     *
     * @param note the value for admin_user.note
     *
     * @mbggenerated Fri May 04 14:15:30 CST 2018
     */
    public void setNote(String note) {
        this.note = note;
    }
}