package jp.co.vermore.entity;

import jp.co.vermore.common.mvc.BaseEntity;

import java.util.Date;

public class BatchStatus extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_status.id
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_status.batch_type
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    private Byte batchType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_status.status
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_status.create_datetime
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_status.update_datetime
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_status.del_flg
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    private Boolean delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_status.note
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    private String note;


    public Byte getBatchType() {
        return batchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_status.batch_type
     *
     * @param batchType the value for batch_status.batch_type
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public void setBatchType(Byte batchType) {
        this.batchType = batchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_status.status
     *
     * @return the value of batch_status.status
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_status.status
     *
     * @param status the value for batch_status.status
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_status.create_datetime
     *
     * @return the value of batch_status.create_datetime
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_status.create_datetime
     *
     * @param createDatetime the value for batch_status.create_datetime
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_status.update_datetime
     *
     * @return the value of batch_status.update_datetime
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_status.update_datetime
     *
     * @param updateDatetime the value for batch_status.update_datetime
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_status.del_flg
     *
     * @return the value of batch_status.del_flg
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_status.del_flg
     *
     * @param delFlg the value for batch_status.del_flg
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_status.note
     *
     * @return the value of batch_status.note
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_status.note
     *
     * @param note the value for batch_status.note
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public void setNote(String note) {
        this.note = note;
    }

    @Override
    public Long getId() {
        return id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }
}