package jp.co.vermore.entity;

import jp.co.vermore.common.mvc.BaseEntity;

import java.util.Date;

public class CoinHistory extends BaseEntity {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_history.coin_id
     *
     * @mbggenerated Tue Apr 03 14:34:53 CST 2018
     */
    private Integer coinId;

    private Long itemId;

    private String serialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_history.user_id
     *
     * @mbggenerated Tue Apr 03 14:34:53 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_history.amount
     *
     * @mbggenerated Tue Apr 03 14:34:53 CST 2018
     */
    private long amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_history.coin_changed
     *
     * @mbggenerated Tue Apr 03 14:34:53 CST 2018
     */
    private long coinChanged;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_history.coin_type
     *
     * @mbggenerated Tue Apr 03 14:34:53 CST 2018
     */
    private Byte coinType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_history.create_datetime
     *
     * @mbggenerated Tue Apr 03 14:34:53 CST 2018
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_history.update_datetime
     *
     * @mbggenerated Tue Apr 03 14:34:53 CST 2018
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_history.del_flg
     *
     * @mbggenerated Tue Apr 03 14:34:53 CST 2018
     */
    private Boolean delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_history.note
     *
     * @mbggenerated Tue Apr 03 14:34:53 CST 2018
     */
    private String note;

    private String uuid;

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_history.coin_id
     *
     * @return the value of coin_history.coin_id
     *
     * @mbggenerated Tue Apr 03 14:34:53 CST 2018
     */
    public Integer getCoinId() {
        return coinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_history.coin_id
     *
     * @param coinId the value for coin_history.coin_id
     *
     * @mbggenerated Tue Apr 03 14:34:53 CST 2018
     */
    public void setCoinId(Integer coinId) {
        this.coinId = coinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_history.user_id
     *
     * @return the value of coin_history.user_id
     *
     * @mbggenerated Tue Apr 03 14:34:53 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_history.user_id
     *
     * @param userId the value for coin_history.user_id
     *
     * @mbggenerated Tue Apr 03 14:34:53 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_history.amount
     *
     * @return the value of coin_history.amount
     *
     * @mbggenerated Tue Apr 03 14:34:53 CST 2018
     */
    public long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_history.amount
     *
     * @param amount the value for coin_history.amount
     *
     * @mbggenerated Tue Apr 03 14:34:53 CST 2018
     */
    public void setAmount(long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_history.coin_changed
     *
     * @return the value of coin_history.coin_changed
     *
     * @mbggenerated Tue Apr 03 14:34:53 CST 2018
     */
    public long getCoinChanged() {
        return coinChanged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_history.coin_changed
     *
     * @param coinChanged the value for coin_history.coin_changed
     *
     * @mbggenerated Tue Apr 03 14:34:53 CST 2018
     */
    public void setCoinChanged(long coinChanged) {
        this.coinChanged = coinChanged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_history.coin_type
     *
     * @return the value of coin_history.coin_type
     *
     * @mbggenerated Tue Apr 03 14:34:53 CST 2018
     */
    public Byte getCoinType() {
        return coinType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_history.coin_type
     *
     * @param coinType the value for coin_history.coin_type
     *
     * @mbggenerated Tue Apr 03 14:34:53 CST 2018
     */
    public void setCoinType(Byte coinType) {
        this.coinType = coinType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_history.create_datetime
     *
     * @return the value of coin_history.create_datetime
     *
     * @mbggenerated Tue Apr 03 14:34:53 CST 2018
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_history.create_datetime
     *
     * @param createDatetime the value for coin_history.create_datetime
     *
     * @mbggenerated Tue Apr 03 14:34:53 CST 2018
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_history.update_datetime
     *
     * @return the value of coin_history.update_datetime
     *
     * @mbggenerated Tue Apr 03 14:34:53 CST 2018
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_history.update_datetime
     *
     * @param updateDatetime the value for coin_history.update_datetime
     *
     * @mbggenerated Tue Apr 03 14:34:53 CST 2018
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_history.del_flg
     *
     * @return the value of coin_history.del_flg
     *
     * @mbggenerated Tue Apr 03 14:34:53 CST 2018
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_history.del_flg
     *
     * @param delFlg the value for coin_history.del_flg
     *
     * @mbggenerated Tue Apr 03 14:34:53 CST 2018
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_history.note
     *
     * @return the value of coin_history.note
     *
     * @mbggenerated Tue Apr 03 14:34:53 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_history.note
     *
     * @param note the value for coin_history.note
     *
     * @mbggenerated Tue Apr 03 14:34:53 CST 2018
     */
    public void setNote(String note) {
        this.note = note;
    }

    public String getSerialNumber() {
        return serialNumber;
    }

    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }

    public Long getItemId() {
        return itemId;
    }

    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }
}