package jp.co.vermore.entity;

import jp.co.vermore.common.mvc.BaseEntity;

import java.util.Date;

public class Comment extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.item_id
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_type
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    private Byte commentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.sort_score
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    private Integer sortScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.desc
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.pic_url1
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    private String picUrl1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.pic_url2
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    private String picUrl2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.publish_start
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    private Date publishStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.publish_end
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    private Date publishEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.create_datetime
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.update_datetime
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.del_flg
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    private Boolean delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.note
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.item_id
     *
     * @return the value of comment.item_id
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.item_id
     *
     * @param itemId the value for comment.item_id
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_type
     *
     * @return the value of comment.comment_type
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    public Byte getCommentType() {
        return commentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_type
     *
     * @param commentType the value for comment.comment_type
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    public void setCommentType(Byte commentType) {
        this.commentType = commentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.sort_score
     *
     * @return the value of comment.sort_score
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    public Integer getSortScore() {
        return sortScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.sort_score
     *
     * @param sortScore the value for comment.sort_score
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    public void setSortScore(Integer sortScore) {
        this.sortScore = sortScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.desc
     *
     * @return the value of comment.desc
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.desc
     *
     * @param desc the value for comment.desc
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.pic_url1
     *
     * @return the value of comment.pic_url1
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    public String getPicUrl1() {
        return picUrl1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.pic_url1
     *
     * @param picUrl1 the value for comment.pic_url1
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    public void setPicUrl1(String picUrl1) {
        this.picUrl1 = picUrl1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.pic_url2
     *
     * @return the value of comment.pic_url2
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    public String getPicUrl2() {
        return picUrl2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.pic_url2
     *
     * @param picUrl2 the value for comment.pic_url2
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    public void setPicUrl2(String picUrl2) {
        this.picUrl2 = picUrl2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.publish_start
     *
     * @return the value of comment.publish_start
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    public Date getPublishStart() {
        return publishStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.publish_start
     *
     * @param publishStart the value for comment.publish_start
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    public void setPublishStart(Date publishStart) {
        this.publishStart = publishStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.publish_end
     *
     * @return the value of comment.publish_end
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    public Date getPublishEnd() {
        return publishEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.publish_end
     *
     * @param publishEnd the value for comment.publish_end
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    public void setPublishEnd(Date publishEnd) {
        this.publishEnd = publishEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.create_datetime
     *
     * @return the value of comment.create_datetime
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.create_datetime
     *
     * @param createDatetime the value for comment.create_datetime
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.update_datetime
     *
     * @return the value of comment.update_datetime
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.update_datetime
     *
     * @param updateDatetime the value for comment.update_datetime
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.del_flg
     *
     * @return the value of comment.del_flg
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.del_flg
     *
     * @param delFlg the value for comment.del_flg
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.note
     *
     * @return the value of comment.note
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.note
     *
     * @param note the value for comment.note
     *
     * @mbggenerated Mon Mar 19 14:36:21 CST 2018
     */
    public void setNote(String note) {
        this.note = note;
    }
}