package jp.co.vermore.entity;

import jp.co.vermore.common.mvc.BaseEntity;

import java.util.Date;

public class Goods extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.uuid
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.title
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    private String title;

    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.pic_url
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    private String picUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.price
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_type
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    private String goodsType;

    private Integer sortScore;


    private Date publishStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.publish_end
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    private Date publishEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.create_datetime
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.update_datetime
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.del_flg
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    private Boolean delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.note
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.uuid
     *
     * @return the value of goods.uuid
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.uuid
     *
     * @param uuid the value for goods.uuid
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.title
     *
     * @return the value of goods.title
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.title
     *
     * @param title the value for goods.title
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.pic_url
     *
     * @return the value of goods.pic_url
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.pic_url
     *
     * @param picUrl the value for goods.pic_url
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.price
     *
     * @return the value of goods.price
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.price
     *
     * @param price the value for goods.price
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_type
     *
     * @return the value of goods.goods_type
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    public String getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_type
     *
     * @param goodsType the value for goods.goods_type
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    public void setGoodsType(String goodsType) {
        this.goodsType = goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.publish_start
     *
     * @return the value of goods.publish_start
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    public Date getPublishStart() {
        return publishStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.publish_start
     *
     * @param publishStart the value for goods.publish_start
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    public void setPublishStart(Date publishStart) {
        this.publishStart = publishStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.publish_end
     *
     * @return the value of goods.publish_end
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    public Date getPublishEnd() {
        return publishEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.publish_end
     *
     * @param publishEnd the value for goods.publish_end
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    public void setPublishEnd(Date publishEnd) {
        this.publishEnd = publishEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.create_datetime
     *
     * @return the value of goods.create_datetime
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.create_datetime
     *
     * @param createDatetime the value for goods.create_datetime
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.update_datetime
     *
     * @return the value of goods.update_datetime
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.update_datetime
     *
     * @param updateDatetime the value for goods.update_datetime
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.del_flg
     *
     * @return the value of goods.del_flg
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.del_flg
     *
     * @param delFlg the value for goods.del_flg
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.note
     *
     * @return the value of goods.note
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.note
     *
     * @param note the value for goods.note
     *
     * @mbggenerated Tue Mar 06 14:10:18 CST 2018
     */
    public void setNote(String note) {
        this.note = note;
    }

    public Integer getSortScore() {
        return sortScore;
    }

    public void setSortScore(Integer sortScore) {
        this.sortScore = sortScore;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }
}