package jp.co.vermore.entity;

import java.util.Date;

public class NotifyNow45 {

    private Integer id;

    private Long userId;

    private Long itemId;

    private Byte pushType;

    private Byte notifyType;

    private Byte notifyStatus;

    private Byte pushStatus;

    private Date publishStart;

    private Date publishEnd;

    private Date createDatetime;

    private Date updateDatetime;

    private Boolean delFlg;

    private String note;

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_now45.id
     *
     * @param id the value for notify_now45.id
     *
     * @mbggenerated Mon Oct 08 13:39:50 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_now45.user_id
     *
     * @return the value of notify_now45.user_id
     *
     * @mbggenerated Mon Oct 08 13:39:50 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_now45.user_id
     *
     * @param userId the value for notify_now45.user_id
     *
     * @mbggenerated Mon Oct 08 13:39:50 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_now45.uuid
     *
     * @return the value of notify_now45.uuid
     *
     * @mbggenerated Mon Oct 08 13:39:50 CST 2018
     */

    public Long getItemId() {
        return itemId;
    }

    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_now45.push_type
     *
     * @return the value of notify_now45.push_type
     *
     * @mbggenerated Mon Oct 08 13:39:50 CST 2018
     */
    public Byte getPushType() {
        return pushType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_now45.push_type
     *
     * @param pushType the value for notify_now45.push_type
     *
     * @mbggenerated Mon Oct 08 13:39:50 CST 2018
     */
    public void setPushType(Byte pushType) {
        this.pushType = pushType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_now45.notify_type
     *
     * @return the value of notify_now45.notify_type
     *
     * @mbggenerated Mon Oct 08 13:39:50 CST 2018
     */
    public Byte getNotifyType() {
        return notifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_now45.notify_type
     *
     * @param notifyType the value for notify_now45.notify_type
     *
     * @mbggenerated Mon Oct 08 13:39:50 CST 2018
     */
    public void setNotifyType(Byte notifyType) {
        this.notifyType = notifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_now45.notify_status
     *
     * @return the value of notify_now45.notify_status
     *
     * @mbggenerated Mon Oct 08 13:39:50 CST 2018
     */
    public Byte getNotifyStatus() {
        return notifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_now45.notify_status
     *
     * @param notifyStatus the value for notify_now45.notify_status
     *
     * @mbggenerated Mon Oct 08 13:39:50 CST 2018
     */
    public void setNotifyStatus(Byte notifyStatus) {
        this.notifyStatus = notifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_now45.push_status
     *
     * @return the value of notify_now45.push_status
     *
     * @mbggenerated Mon Oct 08 13:39:50 CST 2018
     */
    public Byte getPushStatus() {
        return pushStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_now45.push_status
     *
     * @param pushStatus the value for notify_now45.push_status
     *
     * @mbggenerated Mon Oct 08 13:39:50 CST 2018
     */
    public void setPushStatus(Byte pushStatus) {
        this.pushStatus = pushStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_now45.publish_start
     *
     * @return the value of notify_now45.publish_start
     *
     * @mbggenerated Mon Oct 08 13:39:50 CST 2018
     */
    public Date getPublishStart() {
        return publishStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_now45.publish_start
     *
     * @param publishStart the value for notify_now45.publish_start
     *
     * @mbggenerated Mon Oct 08 13:39:50 CST 2018
     */
    public void setPublishStart(Date publishStart) {
        this.publishStart = publishStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_now45.publish_end
     *
     * @return the value of notify_now45.publish_end
     *
     * @mbggenerated Mon Oct 08 13:39:50 CST 2018
     */
    public Date getPublishEnd() {
        return publishEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_now45.publish_end
     *
     * @param publishEnd the value for notify_now45.publish_end
     *
     * @mbggenerated Mon Oct 08 13:39:50 CST 2018
     */
    public void setPublishEnd(Date publishEnd) {
        this.publishEnd = publishEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_now45.create_datetime
     *
     * @return the value of notify_now45.create_datetime
     *
     * @mbggenerated Mon Oct 08 13:39:50 CST 2018
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_now45.create_datetime
     *
     * @param createDatetime the value for notify_now45.create_datetime
     *
     * @mbggenerated Mon Oct 08 13:39:50 CST 2018
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_now45.update_datetime
     *
     * @return the value of notify_now45.update_datetime
     *
     * @mbggenerated Mon Oct 08 13:39:50 CST 2018
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_now45.update_datetime
     *
     * @param updateDatetime the value for notify_now45.update_datetime
     *
     * @mbggenerated Mon Oct 08 13:39:50 CST 2018
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_now45.del_flg
     *
     * @return the value of notify_now45.del_flg
     *
     * @mbggenerated Mon Oct 08 13:39:50 CST 2018
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_now45.del_flg
     *
     * @param delFlg the value for notify_now45.del_flg
     *
     * @mbggenerated Mon Oct 08 13:39:50 CST 2018
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_now45.note
     *
     * @return the value of notify_now45.note
     *
     * @mbggenerated Mon Oct 08 13:39:50 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_now45.note
     *
     * @param note the value for notify_now45.note
     *
     * @mbggenerated Mon Oct 08 13:39:50 CST 2018
     */
    public void setNote(String note) {
        this.note = note;
    }
}