package jp.co.vermore.entity;

import java.util.Date;

public class NotificationDevice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification_device.id
     *
     * @mbggenerated Wed Apr 18 18:28:51 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification_device.user_id
     *
     * @mbggenerated Wed Apr 18 18:28:51 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification_device.user_type
     *
     * @mbggenerated Wed Apr 18 18:28:51 CST 2018
     */
    private Integer userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification_device.device_id
     *
     * @mbggenerated Wed Apr 18 18:28:51 CST 2018
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification_device.os
     *
     * @mbggenerated Wed Apr 18 18:28:51 CST 2018
     */
    private Byte os;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification_device.token
     *
     * @mbggenerated Wed Apr 18 18:28:51 CST 2018
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification_device.create_datetime
     *
     * @mbggenerated Wed Apr 18 18:28:51 CST 2018
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification_device.update_datetime
     *
     * @mbggenerated Wed Apr 18 18:28:51 CST 2018
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification_device.del_flg
     *
     * @mbggenerated Wed Apr 18 18:28:51 CST 2018
     */
    private Boolean delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification_device.note
     *
     * @mbggenerated Wed Apr 18 18:28:51 CST 2018
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification_device.id
     *
     * @return the value of notification_device.id
     *
     * @mbggenerated Wed Apr 18 18:28:51 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification_device.id
     *
     * @param id the value for notification_device.id
     *
     * @mbggenerated Wed Apr 18 18:28:51 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification_device.user_id
     *
     * @return the value of notification_device.user_id
     *
     * @mbggenerated Wed Apr 18 18:28:51 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification_device.user_id
     *
     * @param userId the value for notification_device.user_id
     *
     * @mbggenerated Wed Apr 18 18:28:51 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification_device.user_type
     *
     * @return the value of notification_device.user_type
     *
     * @mbggenerated Wed Apr 18 18:28:51 CST 2018
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification_device.user_type
     *
     * @param userType the value for notification_device.user_type
     *
     * @mbggenerated Wed Apr 18 18:28:51 CST 2018
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification_device.device_id
     *
     * @return the value of notification_device.device_id
     *
     * @mbggenerated Wed Apr 18 18:28:51 CST 2018
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification_device.device_id
     *
     * @param deviceId the value for notification_device.device_id
     *
     * @mbggenerated Wed Apr 18 18:28:51 CST 2018
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification_device.os
     *
     * @return the value of notification_device.os
     *
     * @mbggenerated Wed Apr 18 18:28:51 CST 2018
     */
    public Byte getOs() {
        return os;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification_device.os
     *
     * @param os the value for notification_device.os
     *
     * @mbggenerated Wed Apr 18 18:28:51 CST 2018
     */
    public void setOs(Byte os) {
        this.os = os;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification_device.token
     *
     * @return the value of notification_device.token
     *
     * @mbggenerated Wed Apr 18 18:28:51 CST 2018
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification_device.token
     *
     * @param token the value for notification_device.token
     *
     * @mbggenerated Wed Apr 18 18:28:51 CST 2018
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification_device.create_datetime
     *
     * @return the value of notification_device.create_datetime
     *
     * @mbggenerated Wed Apr 18 18:28:51 CST 2018
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification_device.create_datetime
     *
     * @param createDatetime the value for notification_device.create_datetime
     *
     * @mbggenerated Wed Apr 18 18:28:51 CST 2018
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification_device.update_datetime
     *
     * @return the value of notification_device.update_datetime
     *
     * @mbggenerated Wed Apr 18 18:28:51 CST 2018
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification_device.update_datetime
     *
     * @param updateDatetime the value for notification_device.update_datetime
     *
     * @mbggenerated Wed Apr 18 18:28:51 CST 2018
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification_device.del_flg
     *
     * @return the value of notification_device.del_flg
     *
     * @mbggenerated Wed Apr 18 18:28:51 CST 2018
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification_device.del_flg
     *
     * @param delFlg the value for notification_device.del_flg
     *
     * @mbggenerated Wed Apr 18 18:28:51 CST 2018
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification_device.note
     *
     * @return the value of notification_device.note
     *
     * @mbggenerated Wed Apr 18 18:28:51 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification_device.note
     *
     * @param note the value for notification_device.note
     *
     * @mbggenerated Wed Apr 18 18:28:51 CST 2018
     */
    public void setNote(String note) {
        this.note = note;
    }
}