package jp.co.vermore.entity;

import java.util.Date;

public class Notification {

    private Long id;

    private Long userId;

    private Integer userType;

    private Integer itemId;

    private Long notifiContentId;

    private Byte notifyType;

    private Byte notifiedDevice;

    private Byte notifyStatus;

    private Byte pushStatus;

    private Date publishStart;

    private Date publishEnd;

    private Date createDatetime;

    private Date updateDatetime;

    private Boolean delFlg;

    private String note;

    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.id
     *
     * @param id the value for notification.id
     *
     * @mbggenerated Wed Apr 18 18:50:41 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.user_id
     *
     * @return the value of notification.user_id
     *
     * @mbggenerated Wed Apr 18 18:50:41 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.user_id
     *
     * @param userId the value for notification.user_id
     *
     * @mbggenerated Wed Apr 18 18:50:41 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.user_type
     *
     * @return the value of notification.user_type
     *
     * @mbggenerated Wed Apr 18 18:50:41 CST 2018
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.user_type
     *
     * @param userType the value for notification.user_type
     *
     * @mbggenerated Wed Apr 18 18:50:41 CST 2018
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.notifi_content_id
     *
     * @return the value of notification.notifi_content_id
     *
     * @mbggenerated Wed Apr 18 18:50:41 CST 2018
     */
    public Long getNotifiContentId() {
        return notifiContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.notifi_content_id
     *
     * @param notifiContentId the value for notification.notifi_content_id
     *
     * @mbggenerated Wed Apr 18 18:50:41 CST 2018
     */
    public void setNotifiContentId(Long notifiContentId) {
        this.notifiContentId = notifiContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.notify_type
     *
     * @return the value of notification.notify_type
     *
     * @mbggenerated Wed Apr 18 18:50:41 CST 2018
     */
    public Byte getNotifyType() {
        return notifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.notify_type
     *
     * @param notifyType the value for notification.notify_type
     *
     * @mbggenerated Wed Apr 18 18:50:41 CST 2018
     */
    public void setNotifyType(Byte notifyType) {
        this.notifyType = notifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.notify_status
     *
     * @return the value of notification.notify_status
     *
     * @mbggenerated Wed Apr 18 18:50:41 CST 2018
     */
    public Byte getNotifyStatus() {
        return notifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.notify_status
     *
     * @param notifyStatus the value for notification.notify_status
     *
     * @mbggenerated Wed Apr 18 18:50:41 CST 2018
     */
    public void setNotifyStatus(Byte notifyStatus) {
        this.notifyStatus = notifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.push_status
     *
     * @return the value of notification.push_status
     *
     * @mbggenerated Wed Apr 18 18:50:41 CST 2018
     */
    public Byte getPushStatus() {
        return pushStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.push_status
     *
     * @param pushStatus the value for notification.push_status
     *
     * @mbggenerated Wed Apr 18 18:50:41 CST 2018
     */
    public void setPushStatus(Byte pushStatus) {
        this.pushStatus = pushStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.publish_start
     *
     * @return the value of notification.publish_start
     *
     * @mbggenerated Wed Apr 18 18:50:41 CST 2018
     */
    public Date getPublishStart() {
        return publishStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.publish_start
     *
     * @param publishStart the value for notification.publish_start
     *
     * @mbggenerated Wed Apr 18 18:50:41 CST 2018
     */
    public void setPublishStart(Date publishStart) {
        this.publishStart = publishStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.publish_end
     *
     * @return the value of notification.publish_end
     *
     * @mbggenerated Wed Apr 18 18:50:41 CST 2018
     */
    public Date getPublishEnd() {
        return publishEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.publish_end
     *
     * @param publishEnd the value for notification.publish_end
     *
     * @mbggenerated Wed Apr 18 18:50:41 CST 2018
     */
    public void setPublishEnd(Date publishEnd) {
        this.publishEnd = publishEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.create_datetime
     *
     * @return the value of notification.create_datetime
     *
     * @mbggenerated Wed Apr 18 18:50:41 CST 2018
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.create_datetime
     *
     * @param createDatetime the value for notification.create_datetime
     *
     * @mbggenerated Wed Apr 18 18:50:41 CST 2018
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.update_datetime
     *
     * @return the value of notification.update_datetime
     *
     * @mbggenerated Wed Apr 18 18:50:41 CST 2018
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.update_datetime
     *
     * @param updateDatetime the value for notification.update_datetime
     *
     * @mbggenerated Wed Apr 18 18:50:41 CST 2018
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.del_flg
     *
     * @return the value of notification.del_flg
     *
     * @mbggenerated Wed Apr 18 18:50:41 CST 2018
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.del_flg
     *
     * @param delFlg the value for notification.del_flg
     *
     * @mbggenerated Wed Apr 18 18:50:41 CST 2018
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.note
     *
     * @return the value of notification.note
     *
     * @mbggenerated Wed Apr 18 18:50:41 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.note
     *
     * @param note the value for notification.note
     *
     * @mbggenerated Wed Apr 18 18:50:41 CST 2018
     */
    public void setNote(String note) {
        this.note = note;
    }

    public Byte getNotifiedDevice() {
        return notifiedDevice;
    }

    public void setNotifiedDevice(Byte notifiedDevice) {
        this.notifiedDevice = notifiedDevice;
    }

    public Integer getItemId() {
        return itemId;
    }

    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

}