package jp.co.vermore.entity;

import jp.co.vermore.common.mvc.BaseEntity;

import java.util.Date;

public class OneTimeKey extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column one_time_key.id
     *
     * @mbggenerated Fri Apr 27 02:50:50 JST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column one_time_key.type
     *
     * @mbggenerated Fri Apr 27 02:50:50 JST 2018
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column one_time_key.token
     *
     * @mbggenerated Fri Apr 27 02:50:50 JST 2018
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column one_time_key.mail
     *
     * @mbggenerated Fri Apr 27 02:50:50 JST 2018
     */
    private String mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column one_time_key.expire_datetime
     *
     * @mbggenerated Fri Apr 27 02:50:50 JST 2018
     */
    private Date expireDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column one_time_key.create_datetime
     *
     * @mbggenerated Fri Apr 27 02:50:50 JST 2018
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column one_time_key.update_datetime
     *
     * @mbggenerated Fri Apr 27 02:50:50 JST 2018
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column one_time_key.del_flg
     *
     * @mbggenerated Fri Apr 27 02:50:50 JST 2018
     */
    private Boolean delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column one_time_key.note
     *
     * @mbggenerated Fri Apr 27 02:50:50 JST 2018
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column one_time_key.id
     *
     * @return the value of one_time_key.id
     *
     * @mbggenerated Fri Apr 27 02:50:50 JST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column one_time_key.id
     *
     * @param id the value for one_time_key.id
     *
     * @mbggenerated Fri Apr 27 02:50:50 JST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column one_time_key.type
     *
     * @return the value of one_time_key.type
     *
     * @mbggenerated Fri Apr 27 02:50:50 JST 2018
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column one_time_key.type
     *
     * @param type the value for one_time_key.type
     *
     * @mbggenerated Fri Apr 27 02:50:50 JST 2018
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column one_time_key.token
     *
     * @return the value of one_time_key.token
     *
     * @mbggenerated Fri Apr 27 02:50:50 JST 2018
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column one_time_key.token
     *
     * @param token the value for one_time_key.token
     *
     * @mbggenerated Fri Apr 27 02:50:50 JST 2018
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column one_time_key.mail
     *
     * @return the value of one_time_key.mail
     *
     * @mbggenerated Fri Apr 27 02:50:50 JST 2018
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column one_time_key.mail
     *
     * @param mail the value for one_time_key.mail
     *
     * @mbggenerated Fri Apr 27 02:50:50 JST 2018
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column one_time_key.expire_datetime
     *
     * @return the value of one_time_key.expire_datetime
     *
     * @mbggenerated Fri Apr 27 02:50:50 JST 2018
     */
    public Date getExpireDatetime() {
        return expireDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column one_time_key.expire_datetime
     *
     * @param expireDatetime the value for one_time_key.expire_datetime
     *
     * @mbggenerated Fri Apr 27 02:50:50 JST 2018
     */
    public void setExpireDatetime(Date expireDatetime) {
        this.expireDatetime = expireDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column one_time_key.create_datetime
     *
     * @return the value of one_time_key.create_datetime
     *
     * @mbggenerated Fri Apr 27 02:50:50 JST 2018
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column one_time_key.create_datetime
     *
     * @param createDatetime the value for one_time_key.create_datetime
     *
     * @mbggenerated Fri Apr 27 02:50:50 JST 2018
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column one_time_key.update_datetime
     *
     * @return the value of one_time_key.update_datetime
     *
     * @mbggenerated Fri Apr 27 02:50:50 JST 2018
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column one_time_key.update_datetime
     *
     * @param updateDatetime the value for one_time_key.update_datetime
     *
     * @mbggenerated Fri Apr 27 02:50:50 JST 2018
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column one_time_key.del_flg
     *
     * @return the value of one_time_key.del_flg
     *
     * @mbggenerated Fri Apr 27 02:50:50 JST 2018
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column one_time_key.del_flg
     *
     * @param delFlg the value for one_time_key.del_flg
     *
     * @mbggenerated Fri Apr 27 02:50:50 JST 2018
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column one_time_key.note
     *
     * @return the value of one_time_key.note
     *
     * @mbggenerated Fri Apr 27 02:50:50 JST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column one_time_key.note
     *
     * @param note the value for one_time_key.note
     *
     * @mbggenerated Fri Apr 27 02:50:50 JST 2018
     */
    public void setNote(String note) {
        this.note = note;
    }
}