package jp.co.vermore.entity;

import jp.co.vermore.common.mvc.BaseEntity;

import java.util.Date;

public class Pic extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic.id
     *
     * @mbggenerated Wed May 16 18:43:18 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic.item_id
     *
     * @mbggenerated Wed May 16 18:43:18 CST 2018
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic.item_type
     *
     * @mbggenerated Wed May 16 18:43:18 CST 2018
     */
    private Byte itemType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic.pic_url
     *
     * @mbggenerated Wed May 16 18:43:18 CST 2018
     */
    private String picUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic.create_datetime
     *
     * @mbggenerated Wed May 16 18:43:18 CST 2018
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic.update_datetime
     *
     * @mbggenerated Wed May 16 18:43:18 CST 2018
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic.del_flg
     *
     * @mbggenerated Wed May 16 18:43:18 CST 2018
     */
    private Boolean delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic.note
     *
     * @mbggenerated Wed May 16 18:43:18 CST 2018
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic.id
     *
     * @return the value of pic.id
     *
     * @mbggenerated Wed May 16 18:43:18 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic.id
     *
     * @param id the value for pic.id
     *
     * @mbggenerated Wed May 16 18:43:18 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic.item_id
     *
     * @return the value of pic.item_id
     *
     * @mbggenerated Wed May 16 18:43:18 CST 2018
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic.item_id
     *
     * @param itemId the value for pic.item_id
     *
     * @mbggenerated Wed May 16 18:43:18 CST 2018
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic.item_type
     *
     * @return the value of pic.item_type
     *
     * @mbggenerated Wed May 16 18:43:18 CST 2018
     */
    public Byte getItemType() {
        return itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic.item_type
     *
     * @param itemType the value for pic.item_type
     *
     * @mbggenerated Wed May 16 18:43:18 CST 2018
     */
    public void setItemType(Byte itemType) {
        this.itemType = itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic.pic_url
     *
     * @return the value of pic.pic_url
     *
     * @mbggenerated Wed May 16 18:43:18 CST 2018
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic.pic_url
     *
     * @param picUrl the value for pic.pic_url
     *
     * @mbggenerated Wed May 16 18:43:18 CST 2018
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic.create_datetime
     *
     * @return the value of pic.create_datetime
     *
     * @mbggenerated Wed May 16 18:43:18 CST 2018
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic.create_datetime
     *
     * @param createDatetime the value for pic.create_datetime
     *
     * @mbggenerated Wed May 16 18:43:18 CST 2018
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic.update_datetime
     *
     * @return the value of pic.update_datetime
     *
     * @mbggenerated Wed May 16 18:43:18 CST 2018
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic.update_datetime
     *
     * @param updateDatetime the value for pic.update_datetime
     *
     * @mbggenerated Wed May 16 18:43:18 CST 2018
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic.del_flg
     *
     * @return the value of pic.del_flg
     *
     * @mbggenerated Wed May 16 18:43:18 CST 2018
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic.del_flg
     *
     * @param delFlg the value for pic.del_flg
     *
     * @mbggenerated Wed May 16 18:43:18 CST 2018
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic.note
     *
     * @return the value of pic.note
     *
     * @mbggenerated Wed May 16 18:43:18 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic.note
     *
     * @param note the value for pic.note
     *
     * @mbggenerated Wed May 16 18:43:18 CST 2018
     */
    public void setNote(String note) {
        this.note = note;
    }
}