package jp.co.vermore.entity;

import jp.co.vermore.common.mvc.BaseEntity;

import java.util.Date;

public class Place extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.id
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.uuid
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.name
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.introduce
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    private String introduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.address
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.area
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    private Integer area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.pic_url
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    private String picUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.flic_url
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    private String flicUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.create_datetime
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.update_datetime
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.del_flg
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    private Boolean delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.note
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    private String note;

    private String coordinate1;

    private String coordinate2;

    private Date publishStart;

    private Date publishEnd;


    public Date getPublishStart() {
        return publishStart;
    }

    public void setPublishStart(Date publishStart) {
        this.publishStart = publishStart;
    }

    public Date getPublishEnd() {
        return publishEnd;
    }

    public void setPublishEnd(Date publishEnd) {
        this.publishEnd = publishEnd;
    }

    public String getCoordinate1() {
        return coordinate1;
    }

    public void setCoordinate1(String coordinate1) {
        this.coordinate1 = coordinate1;
    }

    public String getCoordinate2() {
        return coordinate2;
    }

    public void setCoordinate2(String coordinate2) {
        this.coordinate2 = coordinate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.id
     *
     * @return the value of place.id
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.id
     *
     * @param id the value for place.id
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.uuid
     *
     * @return the value of place.uuid
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.uuid
     *
     * @param uuid the value for place.uuid
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.name
     *
     * @return the value of place.name
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.name
     *
     * @param name the value for place.name
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.introduce
     *
     * @return the value of place.introduce
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.introduce
     *
     * @param introduce the value for place.introduce
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.address
     *
     * @return the value of place.address
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.address
     *
     * @param address the value for place.address
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.area
     *
     * @return the value of place.area
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    public Integer getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.area
     *
     * @param area the value for place.area
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    public void setArea(Integer area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.pic_url
     *
     * @return the value of place.pic_url
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.pic_url
     *
     * @param picUrl the value for place.pic_url
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.flic_url
     *
     * @return the value of place.flic_url
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    public String getFlicUrl() {
        return flicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.flic_url
     *
     * @param flicUrl the value for place.flic_url
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    public void setFlicUrl(String flicUrl) {
        this.flicUrl = flicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.create_datetime
     *
     * @return the value of place.create_datetime
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.create_datetime
     *
     * @param createDatetime the value for place.create_datetime
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.update_datetime
     *
     * @return the value of place.update_datetime
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.update_datetime
     *
     * @param updateDatetime the value for place.update_datetime
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.del_flg
     *
     * @return the value of place.del_flg
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.del_flg
     *
     * @param delFlg the value for place.del_flg
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.note
     *
     * @return the value of place.note
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.note
     *
     * @param note the value for place.note
     *
     * @mbggenerated Tue Mar 20 16:16:55 CST 2018
     */
    public void setNote(String note) {
        this.note = note;
    }
}