package jp.co.vermore.entity;

import java.util.Date;

public class RandomShopTwo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column random_shop_two.id
     *
     * @mbggenerated Wed Aug 08 14:43:58 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column random_shop_two.shop_type
     *
     * @mbggenerated Wed Aug 08 14:43:58 CST 2018
     */
    private Byte shopType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column random_shop_two.uuid
     *
     * @mbggenerated Wed Aug 08 14:43:58 CST 2018
     */
    private String uuid;

    private Byte area;

    private Byte now4;

    private Byte now5;

    private Date publishStart;

    private Date publishEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column random_shop_two.create_datetime
     *
     * @mbggenerated Wed Aug 08 14:43:58 CST 2018
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column random_shop_two.update_datetime
     *
     * @mbggenerated Wed Aug 08 14:43:58 CST 2018
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column random_shop_two.del_flg
     *
     * @mbggenerated Wed Aug 08 14:43:58 CST 2018
     */
    private Boolean delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column random_shop_two.note
     *
     * @mbggenerated Wed Aug 08 14:43:58 CST 2018
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column random_shop_two.id
     *
     * @return the value of random_shop_two.id
     *
     * @mbggenerated Wed Aug 08 14:43:58 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column random_shop_two.id
     *
     * @param id the value for random_shop_two.id
     *
     * @mbggenerated Wed Aug 08 14:43:58 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column random_shop_two.shop_type
     *
     * @return the value of random_shop_two.shop_type
     *
     * @mbggenerated Wed Aug 08 14:43:58 CST 2018
     */
    public Byte getShopType() {
        return shopType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column random_shop_two.shop_type
     *
     * @param shopType the value for random_shop_two.shop_type
     *
     * @mbggenerated Wed Aug 08 14:43:58 CST 2018
     */
    public void setShopType(Byte shopType) {
        this.shopType = shopType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column random_shop_two.uuid
     *
     * @return the value of random_shop_two.uuid
     *
     * @mbggenerated Wed Aug 08 14:43:58 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column random_shop_two.uuid
     *
     * @param uuid the value for random_shop_two.uuid
     *
     * @mbggenerated Wed Aug 08 14:43:58 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column random_shop_two.create_datetime
     *
     * @return the value of random_shop_two.create_datetime
     *
     * @mbggenerated Wed Aug 08 14:43:58 CST 2018
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column random_shop_two.create_datetime
     *
     * @param createDatetime the value for random_shop_two.create_datetime
     *
     * @mbggenerated Wed Aug 08 14:43:58 CST 2018
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column random_shop_two.update_datetime
     *
     * @return the value of random_shop_two.update_datetime
     *
     * @mbggenerated Wed Aug 08 14:43:58 CST 2018
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column random_shop_two.update_datetime
     *
     * @param updateDatetime the value for random_shop_two.update_datetime
     *
     * @mbggenerated Wed Aug 08 14:43:58 CST 2018
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column random_shop_two.del_flg
     *
     * @return the value of random_shop_two.del_flg
     *
     * @mbggenerated Wed Aug 08 14:43:58 CST 2018
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column random_shop_two.del_flg
     *
     * @param delFlg the value for random_shop_two.del_flg
     *
     * @mbggenerated Wed Aug 08 14:43:58 CST 2018
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column random_shop_two.note
     *
     * @return the value of random_shop_two.note
     *
     * @mbggenerated Wed Aug 08 14:43:58 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column random_shop_two.note
     *
     * @param note the value for random_shop_two.note
     *
     * @mbggenerated Wed Aug 08 14:43:58 CST 2018
     */
    public void setNote(String note) {
        this.note = note;
    }


    public Byte getArea() {
        return area;
    }

    public void setArea(Byte area) {
        this.area = area;
    }

    public Byte getNow4() {
        return now4;
    }

    public void setNow4(Byte now4) {
        this.now4 = now4;
    }

    public Byte getNow5() {
        return now5;
    }

    public void setNow5(Byte now5) {
        this.now5 = now5;
    }

    public Date getPublishStart() {
        return publishStart;
    }

    public void setPublishStart(Date publishStart) {
        this.publishStart = publishStart;
    }

    public Date getPublishEnd() {
        return publishEnd;
    }

    public void setPublishEnd(Date publishEnd) {
        this.publishEnd = publishEnd;
    }

}