package jp.co.vermore.entity;

import jp.co.vermore.common.mvc.BaseEntity;

import java.util.Date;

public class Rise extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rise.id
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    private Long id;

    private String office;

    public void setOffice(String office) {
        this.office = office;
    }

    public String getOffice() {
        return office;
    }

    private Integer sortScore;

    public void setSortScore(Integer sortScore) {
        this.sortScore = sortScore;
    }

    public Integer getSortScore() {
        return sortScore;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rise.name1
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    private String name1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rise.name2
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    private String name2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rise.pic_url
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    private String picUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rise.category
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rise.publish_start
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    private Date publishStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rise.publish_end
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    private Date publishEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rise.create_datetime
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rise.update_datetime
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rise.del_flg
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    private Boolean delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rise.note
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rise.id
     *
     * @return the value of rise.id
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rise.id
     *
     * @param id the value for rise.id
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rise.name1
     *
     * @return the value of rise.name1
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public String getName1() {
        return name1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rise.name1
     *
     * @param name1 the value for rise.name1
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setName1(String name1) {
        this.name1 = name1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rise.name2
     *
     * @return the value of rise.name2
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public String getName2() {
        return name2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rise.name2
     *
     * @param name2 the value for rise.name2
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setName2(String name2) {
        this.name2 = name2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rise.pic_url
     *
     * @return the value of rise.pic_url
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rise.pic_url
     *
     * @param picUrl the value for rise.pic_url
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rise.category
     *
     * @return the value of rise.category
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rise.category
     *
     * @param category the value for rise.category
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rise.publish_start
     *
     * @return the value of rise.publish_start
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public Date getPublishStart() {
        return publishStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rise.publish_start
     *
     * @param publishStart the value for rise.publish_start
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setPublishStart(Date publishStart) {
        this.publishStart = publishStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rise.publish_end
     *
     * @return the value of rise.publish_end
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public Date getPublishEnd() {
        return publishEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rise.publish_end
     *
     * @param publishEnd the value for rise.publish_end
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setPublishEnd(Date publishEnd) {
        this.publishEnd = publishEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rise.create_datetime
     *
     * @return the value of rise.create_datetime
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rise.create_datetime
     *
     * @param createDatetime the value for rise.create_datetime
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rise.update_datetime
     *
     * @return the value of rise.update_datetime
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rise.update_datetime
     *
     * @param updateDatetime the value for rise.update_datetime
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rise.del_flg
     *
     * @return the value of rise.del_flg
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rise.del_flg
     *
     * @param delFlg the value for rise.del_flg
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rise.note
     *
     * @return the value of rise.note
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rise.note
     *
     * @param note the value for rise.note
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setNote(String note) {
        this.note = note;
    }
}