package jp.co.vermore.entity;

import jp.co.vermore.common.mvc.BaseEntity;

import java.util.Date;

public class SessionId extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session_id.id
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session_id.uuid
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session_id.session_id
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    private String sessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session_id.expire_datetime
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    private Date expireDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session_id.create_datetime
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session_id.update_datetime
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session_id.del_flg
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    private Boolean delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session_id.note
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session_id.id
     *
     * @return the value of session_id.id
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session_id.id
     *
     * @param id the value for session_id.id
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session_id.uuid
     *
     * @return the value of session_id.uuid
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session_id.uuid
     *
     * @param uuid the value for session_id.uuid
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session_id.session_id
     *
     * @return the value of session_id.session_id
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session_id.session_id
     *
     * @param sessionId the value for session_id.session_id
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session_id.expire_datetime
     *
     * @return the value of session_id.expire_datetime
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public Date getExpireDatetime() {
        return expireDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session_id.expire_datetime
     *
     * @param expireDatetime the value for session_id.expire_datetime
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setExpireDatetime(Date expireDatetime) {
        this.expireDatetime = expireDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session_id.create_datetime
     *
     * @return the value of session_id.create_datetime
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session_id.create_datetime
     *
     * @param createDatetime the value for session_id.create_datetime
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session_id.update_datetime
     *
     * @return the value of session_id.update_datetime
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session_id.update_datetime
     *
     * @param updateDatetime the value for session_id.update_datetime
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session_id.del_flg
     *
     * @return the value of session_id.del_flg
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session_id.del_flg
     *
     * @param delFlg the value for session_id.del_flg
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session_id.note
     *
     * @return the value of session_id.note
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session_id.note
     *
     * @param note the value for session_id.note
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setNote(String note) {
        this.note = note;
    }
}