package jp.co.vermore.entity;

import jp.co.vermore.common.mvc.BaseEntity;

import java.util.Date;

public class Settlement extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement.id
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement.customer_id
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    private Long customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement.item_type
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    private Byte itemType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement.item_id
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement.type
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement.amount
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement.yyyymm
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    private Integer yyyymm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement.status
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement.method
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    private Byte method;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement.title
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement.content
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement.create_datetime
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement.update_datetime
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement.del_flg
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    private Boolean delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement.note
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    private String note;

    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement.customer_id
     *
     * @param customerId the value for settlement.customer_id
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement.item_type
     *
     * @return the value of settlement.item_type
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public Byte getItemType() {
        return itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement.item_type
     *
     * @param itemType the value for settlement.item_type
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public void setItemType(Byte itemType) {
        this.itemType = itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement.item_id
     *
     * @return the value of settlement.item_id
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement.item_id
     *
     * @param itemId the value for settlement.item_id
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement.type
     *
     * @return the value of settlement.type
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement.type
     *
     * @param type the value for settlement.type
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement.amount
     *
     * @return the value of settlement.amount
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement.amount
     *
     * @param amount the value for settlement.amount
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement.yyyymm
     *
     * @return the value of settlement.yyyymm
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public Integer getYyyymm() {
        return yyyymm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement.yyyymm
     *
     * @param yyyymm the value for settlement.yyyymm
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public void setYyyymm(Integer yyyymm) {
        this.yyyymm = yyyymm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement.status
     *
     * @return the value of settlement.status
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement.status
     *
     * @param status the value for settlement.status
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement.method
     *
     * @return the value of settlement.method
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public Byte getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement.method
     *
     * @param method the value for settlement.method
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public void setMethod(Byte method) {
        this.method = method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement.title
     *
     * @return the value of settlement.title
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement.title
     *
     * @param title the value for settlement.title
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement.content
     *
     * @return the value of settlement.content
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement.content
     *
     * @param content the value for settlement.content
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement.create_datetime
     *
     * @return the value of settlement.create_datetime
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement.create_datetime
     *
     * @param createDatetime the value for settlement.create_datetime
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement.update_datetime
     *
     * @return the value of settlement.update_datetime
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement.update_datetime
     *
     * @param updateDatetime the value for settlement.update_datetime
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement.del_flg
     *
     * @return the value of settlement.del_flg
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement.del_flg
     *
     * @param delFlg the value for settlement.del_flg
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement.note
     *
     * @return the value of settlement.note
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement.note
     *
     * @param note the value for settlement.note
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public void setNote(String note) {
        this.note = note;
    }

    @Override
    public Long getId() {
        return id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }
}