package jp.co.vermore.entity;

import jp.co.vermore.common.mvc.BaseEntity;

import java.util.Date;

public class SettlementMaster extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_master.id
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_master.settlement_type
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    private Byte settlementType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_master.content
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_master.create_datetime
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_master.update_datetime
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_master.del_flg
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    private Boolean delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_master.note
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    private String note;

    public Byte getSettlementType() {
        return settlementType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_master.settlement_type
     *
     * @param settlementType the value for settlement_master.settlement_type
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public void setSettlementType(Byte settlementType) {
        this.settlementType = settlementType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_master.content
     *
     * @return the value of settlement_master.content
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_master.content
     *
     * @param content the value for settlement_master.content
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_master.create_datetime
     *
     * @return the value of settlement_master.create_datetime
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_master.create_datetime
     *
     * @param createDatetime the value for settlement_master.create_datetime
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_master.update_datetime
     *
     * @return the value of settlement_master.update_datetime
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_master.update_datetime
     *
     * @param updateDatetime the value for settlement_master.update_datetime
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_master.del_flg
     *
     * @return the value of settlement_master.del_flg
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_master.del_flg
     *
     * @param delFlg the value for settlement_master.del_flg
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_master.note
     *
     * @return the value of settlement_master.note
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_master.note
     *
     * @param note the value for settlement_master.note
     *
     * @mbggenerated Wed Jun 13 13:05:39 CST 2018
     */
    public void setNote(String note) {
        this.note = note;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
}