package jp.co.vermore.entity;

import jp.co.vermore.common.mvc.BaseEntity;

import java.util.Date;

public class ShopCoupon extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_coupon.id
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_coupon.shop_id
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    private Long shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_coupon.category
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    private Byte category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_coupon.title
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_coupon.pic_url1
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    private String picUrl1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_coupon.desc
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    private String desc;

    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_coupon.publish_start
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    private Date publishStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_coupon.publish_end
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    private Date publishEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_coupon.create_datetime
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_coupon.update_datetime
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_coupon.del_flg
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    private Boolean delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_coupon.note
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    private String note;

    private  String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_coupon.id
     *
     * @return the value of shop_coupon.id
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_coupon.id
     *
     * @param id the value for shop_coupon.id
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_coupon.shop_id
     *
     * @return the value of shop_coupon.shop_id
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_coupon.shop_id
     *
     * @param shopId the value for shop_coupon.shop_id
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_coupon.category
     *
     * @return the value of shop_coupon.category
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public Byte getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_coupon.category
     *
     * @param category the value for shop_coupon.category
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setCategory(Byte category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_coupon.title
     *
     * @return the value of shop_coupon.title
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_coupon.title
     *
     * @param title the value for shop_coupon.title
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_coupon.pic_url1
     *
     * @return the value of shop_coupon.pic_url1
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public String getPicUrl1() {
        return picUrl1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_coupon.pic_url1
     *
     * @param picUrl1 the value for shop_coupon.pic_url1
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setPicUrl1(String picUrl1) {
        this.picUrl1 = picUrl1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_coupon.desc
     *
     * @return the value of shop_coupon.desc
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_coupon.desc
     *
     * @param desc the value for shop_coupon.desc
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_coupon.publish_start
     *
     * @return the value of shop_coupon.publish_start
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public Date getPublishStart() {
        return publishStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_coupon.publish_start
     *
     * @param publishStart the value for shop_coupon.publish_start
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setPublishStart(Date publishStart) {
        this.publishStart = publishStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_coupon.publish_end
     *
     * @return the value of shop_coupon.publish_end
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public Date getPublishEnd() {
        return publishEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_coupon.publish_end
     *
     * @param publishEnd the value for shop_coupon.publish_end
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setPublishEnd(Date publishEnd) {
        this.publishEnd = publishEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_coupon.create_datetime
     *
     * @return the value of shop_coupon.create_datetime
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_coupon.create_datetime
     *
     * @param createDatetime the value for shop_coupon.create_datetime
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_coupon.update_datetime
     *
     * @return the value of shop_coupon.update_datetime
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_coupon.update_datetime
     *
     * @param updateDatetime the value for shop_coupon.update_datetime
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_coupon.del_flg
     *
     * @return the value of shop_coupon.del_flg
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_coupon.del_flg
     *
     * @param delFlg the value for shop_coupon.del_flg
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_coupon.note
     *
     * @return the value of shop_coupon.note
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_coupon.note
     *
     * @param note the value for shop_coupon.note
     *
     * @mbggenerated Wed Feb 28 15:42:55 CST 2018
     */
    public void setNote(String note) {
        this.note = note;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}