package jp.co.vermore.entity;

import jp.co.vermore.common.mvc.BaseEntity;

import java.util.Date;

public class ShopTag extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_tag.id
     *
     * @mbggenerated Mon Mar 12 10:31:55 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_tag.shop_id
     *
     * @mbggenerated Mon Mar 12 10:31:55 CST 2018
     */
    private Long shopId;

    private Byte moduleType;

    private Byte menu1;

    private Byte menu2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_tag.tag_type
     *
     * @mbggenerated Mon Mar 12 10:31:55 CST 2018
     */
    private Byte tagType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_tag.content
     *
     * @mbggenerated Mon Mar 12 10:31:55 CST 2018
     */
    private Integer content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_tag.create_datetime
     *
     * @mbggenerated Mon Mar 12 10:31:55 CST 2018
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_tag.update_datetime
     *
     * @mbggenerated Mon Mar 12 10:31:55 CST 2018
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_tag.del_flg
     *
     * @mbggenerated Mon Mar 12 10:31:55 CST 2018
     */
    private Boolean delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_tag.note
     *
     * @mbggenerated Mon Mar 12 10:31:55 CST 2018
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_tag.id
     *
     * @return the value of shop_tag.id
     *
     * @mbggenerated Mon Mar 12 10:31:55 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_tag.id
     *
     * @param id the value for shop_tag.id
     *
     * @mbggenerated Mon Mar 12 10:31:55 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_tag.shop_id
     *
     * @return the value of shop_tag.shop_id
     *
     * @mbggenerated Mon Mar 12 10:31:55 CST 2018
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_tag.shop_id
     *
     * @param shopId the value for shop_tag.shop_id
     *
     * @mbggenerated Mon Mar 12 10:31:55 CST 2018
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_tag.tag_type
     *
     * @return the value of shop_tag.tag_type
     *
     * @mbggenerated Mon Mar 12 10:31:55 CST 2018
     */
    public Byte getTagType() {
        return tagType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_tag.tag_type
     *
     * @param tagType the value for shop_tag.tag_type
     *
     * @mbggenerated Mon Mar 12 10:31:55 CST 2018
     */
    public void setTagType(Byte tagType) {
        this.tagType = tagType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_tag.content
     *
     * @return the value of shop_tag.content
     *
     * @mbggenerated Mon Mar 12 10:31:55 CST 2018
     */
    public Integer getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_tag.content
     *
     * @param content the value for shop_tag.content
     *
     * @mbggenerated Mon Mar 12 10:31:55 CST 2018
     */
    public void setContent(Integer content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_tag.create_datetime
     *
     * @return the value of shop_tag.create_datetime
     *
     * @mbggenerated Mon Mar 12 10:31:55 CST 2018
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_tag.create_datetime
     *
     * @param createDatetime the value for shop_tag.create_datetime
     *
     * @mbggenerated Mon Mar 12 10:31:55 CST 2018
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_tag.update_datetime
     *
     * @return the value of shop_tag.update_datetime
     *
     * @mbggenerated Mon Mar 12 10:31:55 CST 2018
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_tag.update_datetime
     *
     * @param updateDatetime the value for shop_tag.update_datetime
     *
     * @mbggenerated Mon Mar 12 10:31:55 CST 2018
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_tag.del_flg
     *
     * @return the value of shop_tag.del_flg
     *
     * @mbggenerated Mon Mar 12 10:31:55 CST 2018
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_tag.del_flg
     *
     * @param delFlg the value for shop_tag.del_flg
     *
     * @mbggenerated Mon Mar 12 10:31:55 CST 2018
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_tag.note
     *
     * @return the value of shop_tag.note
     *
     * @mbggenerated Mon Mar 12 10:31:55 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_tag.note
     *
     * @param note the value for shop_tag.note
     *
     * @mbggenerated Mon Mar 12 10:31:55 CST 2018
     */
    public void setNote(String note) {
        this.note = note;
    }


    public Byte getModuleType() {
        return moduleType;
    }

    public void setModuleType(Byte moduleType) {
        this.moduleType = moduleType;
    }

    public Byte getMenu1() {
        return menu1;
    }

    public void setMenu1(Byte menu1) {
        this.menu1 = menu1;
    }

    public Byte getMenu2() {
        return menu2;
    }

    public void setMenu2(Byte menu2) {
        this.menu2 = menu2;
    }

}