package jp.co.vermore.entity;

import jp.co.vermore.common.mvc.BaseEntity;

import java.util.Date;

public class ShopDetail extends BaseEntity {

    private Long id;

    private Integer shopType;

    private Long shopListId;

    private String name;

    private String location;

    private String picUrl1;

    private String picUrl2;

    private String picUrl3;

    private String picUrl4;

    private String picUrl5;

    private String picUrl6;

    private String videoUrl;

    private String videoUrl2;

    private String title;

    private String desc1;

    private String title2;

    private String desc2;

    private String desc3;

    private String desc4;

    private String desc5;

    private String desc6;

    private String desc7;

    private String desc8;

    private String desc9;

    private String desc10;

    private String desc11;

    private String desc12;

    private String desc13;

    private String desc14;

    private String desc15;

    private String desc16;

    private String desc17;

    private String desc18;

    private String desc19;

    private String desc20;

    private String desc21;

    private String desc22;

    private String desc23;

    private String desc24;

    private String desc25;

    private String desc26;

    private String desc27;

    private String desc28;

    private String desc29;

    private String desc30;

    private String desc31;

    private String desc32;

    private String desc33;

    private String desc34;

    private String desc35;

    private String desc36;

    private String desc37;

    private String desc38;

    private String desc39;

    private String desc40;

    private String desc41;

    private String desc42;

    private String desc43;

    private String tel;

    private String address;

    private String now5;

    private Date publishStart;

    private Date publishEnd;

    private Date createDatetime;

    private Date updateDatetime;

    private Boolean delFlg;

    private String note;

    private String category;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getShopListId() {
        return shopListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_detail.shop_id
     *
     * @param shopListId the value for shop_detail.shop_id
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public void setShopListId(Long shopListId) {
        this.shopListId = shopListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_detail.name
     *
     * @return the value of shop_detail.name
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_detail.name
     *
     * @param name the value for shop_detail.name
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_detail.location
     *
     * @return the value of shop_detail.location
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_detail.location
     *
     * @param location the value for shop_detail.location
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_detail.pic_url1
     *
     * @return the value of shop_detail.pic_url1
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public String getPicUrl1() {
        return picUrl1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_detail.pic_url1
     *
     * @param picUrl1 the value for shop_detail.pic_url1
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public void setPicUrl1(String picUrl1) {
        this.picUrl1 = picUrl1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_detail.pic_url2
     *
     * @return the value of shop_detail.pic_url2
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public String getPicUrl2() {
        return picUrl2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_detail.pic_url2
     *
     * @param picUrl2 the value for shop_detail.pic_url2
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public void setPicUrl2(String picUrl2) {
        this.picUrl2 = picUrl2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_detail.pic_url3
     *
     * @return the value of shop_detail.pic_url3
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public String getPicUrl3() {
        return picUrl3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_detail.pic_url3
     *
     * @param picUrl3 the value for shop_detail.pic_url3
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public void setPicUrl3(String picUrl3) {
        this.picUrl3 = picUrl3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_detail.pic_url4
     *
     * @return the value of shop_detail.pic_url4
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public String getPicUrl4() {
        return picUrl4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_detail.pic_url4
     *
     * @param picUrl4 the value for shop_detail.pic_url4
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public void setPicUrl4(String picUrl4) {
        this.picUrl4 = picUrl4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_detail.pic_url5
     *
     * @return the value of shop_detail.pic_url5
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public String getPicUrl5() {
        return picUrl5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_detail.pic_url5
     *
     * @param picUrl5 the value for shop_detail.pic_url5
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public void setPicUrl5(String picUrl5) {
        this.picUrl5 = picUrl5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_detail.pic_url6
     *
     * @return the value of shop_detail.pic_url6
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public String getPicUrl6() {
        return picUrl6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_detail.pic_url6
     *
     * @param picUrl6 the value for shop_detail.pic_url6
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public void setPicUrl6(String picUrl6) {
        this.picUrl6 = picUrl6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_detail.video_url1
     *
     * @return the value of shop_detail.video_url1
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_detail.video_url1
     *
     * @param videoUrl the value for shop_detail.video_url1
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_detail.video_url2
     *
     * @return the value of shop_detail.video_url2
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public String getVideoUrl2() {
        return videoUrl2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_detail.video_url2
     *
     * @param videoUrl2 the value for shop_detail.video_url2
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public void setVideoUrl2(String videoUrl2) {
        this.videoUrl2 = videoUrl2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_detail.title1
     *
     * @return the value of shop_detail.title1
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_detail.title1
     *
     * @param title the value for shop_detail.title1
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public void setTitle1(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_detail.desc1
     *
     * @return the value of shop_detail.desc1
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public String getDesc1() {
        return desc1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_detail.desc1
     *
     * @param desc1 the value for shop_detail.desc1
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public void setDesc1(String desc1) {
        this.desc1 = desc1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_detail.title2
     *
     * @return the value of shop_detail.title2
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public String getTitle2() {
        return title2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_detail.title2
     *
     * @param title2 the value for shop_detail.title2
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public void setTitle2(String title2) {
        this.title2 = title2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_detail.desc2
     *
     * @return the value of shop_detail.desc2
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public String getDesc2() {
        return desc2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_detail.desc2
     *
     * @param desc2 the value for shop_detail.desc2
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public void setDesc2(String desc2) {
        this.desc2 = desc2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_detail.desc3
     *
     * @return the value of shop_detail.desc3
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public String getDesc3() {
        return desc3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_detail.desc3
     *
     * @param desc3 the value for shop_detail.desc3
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public void setDesc3(String desc3) {
        this.desc3 = desc3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_detail.desc4
     *
     * @return the value of shop_detail.desc4
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public String getDesc4() {
        return desc4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_detail.desc4
     *
     * @param desc4 the value for shop_detail.desc4
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public void setDesc4(String desc4) {
        this.desc4 = desc4;
    }



    public String getDesc5() {
        return desc5;
    }

    public void setDesc5(String desc5) {
        this.desc5 = desc5;
    }

    public String getDesc6() {
        return desc6;
    }

    public void setDesc6(String desc6) {
        this.desc6 = desc6;
    }

    public String getDesc7() {
        return desc7;
    }

    public void setDesc7(String desc7) {
        this.desc7 = desc7;
    }

    public String getDesc8() {
        return desc8;
    }

    public void setDesc8(String desc8) {
        this.desc8 = desc8;
    }

    public String getDesc9() {
        return desc9;
    }

    public void setDesc9(String desc9) {
        this.desc9 = desc9;
    }

    public String getDesc10() {
        return desc10;
    }

    public void setDesc10(String desc10) {
        this.desc10 = desc10;
    }

    public String getDesc11() {
        return desc11;
    }

    public void setDesc11(String desc11) {
        this.desc11 = desc11;
    }

    public String getDesc12() {
        return desc12;
    }

    public void setDesc12(String desc12) {
        this.desc12 = desc12;
    }

    public String getDesc13() {
        return desc13;
    }

    public void setDesc13(String desc13) {
        this.desc13 = desc13;
    }

    public String getDesc14() {
        return desc14;
    }

    public void setDesc14(String desc14) {
        this.desc14 = desc14;
    }

    public String getDesc15() {
        return desc15;
    }

    public void setDesc15(String desc15) {
        this.desc15 = desc15;
    }

    public String getDesc16() {
        return desc16;
    }

    public void setDesc16(String desc16) {
        this.desc16 = desc16;
    }

    public String getDesc17() {
        return desc17;
    }

    public void setDesc17(String desc17) {
        this.desc17 = desc17;
    }

    public String getDesc18() {
        return desc18;
    }

    public void setDesc18(String desc18) {
        this.desc18 = desc18;
    }

    public String getDesc19() {
        return desc19;
    }

    public void setDesc19(String desc19) {
        this.desc19 = desc19;
    }

    public String getDesc20() {
        return desc20;
    }

    public void setDesc20(String desc20) {
        this.desc20 = desc20;
    }

    public String getDesc21() {
        return desc21;
    }

    public void setDesc21(String desc21) {
        this.desc21 = desc21;
    }

    public String getDesc22() {
        return desc22;
    }

    public void setDesc22(String desc22) {
        this.desc22 = desc22;
    }

    public String getDesc23() {
        return desc23;
    }

    public void setDesc23(String desc23) {
        this.desc23 = desc23;
    }

    public String getDesc24() {
        return desc24;
    }

    public void setDesc24(String desc24) {
        this.desc24 = desc24;
    }

    public String getDesc25() {
        return desc25;
    }

    public void setDesc25(String desc25) {
        this.desc25 = desc25;
    }

    public String getDesc26() {
        return desc26;
    }

    public void setDesc26(String desc26) {
        this.desc26 = desc26;
    }

    public String getDesc27() {
        return desc27;
    }

    public void setDesc27(String desc27) {
        this.desc27 = desc27;
    }

    public String getDesc28() {
        return desc28;
    }

    public void setDesc28(String desc28) {
        this.desc28 = desc28;
    }

    public String getDesc29() {
        return desc29;
    }

    public void setDesc29(String desc29) {
        this.desc29 = desc29;
    }

    public String getDesc30() {
        return desc30;
    }

    public void setDesc30(String desc30) {
        this.desc30 = desc30;
    }

    public String getDesc31() {
        return desc31;
    }

    public void setDesc31(String desc31) {
        this.desc31 = desc31;
    }

    public String getDesc32() {
        return desc32;
    }

    public void setDesc32(String desc32) {
        this.desc32 = desc32;
    }

    public String getDesc33() {
        return desc33;
    }

    public void setDesc33(String desc33) {
        this.desc33 = desc33;
    }

    public String getDesc34() {
        return desc34;
    }

    public void setDesc34(String desc34) {
        this.desc34 = desc34;
    }

    public String getDesc35() {
        return desc35;
    }

    public void setDesc35(String desc35) {
        this.desc35 = desc35;
    }

    public String getDesc36() {
        return desc36;
    }

    public void setDesc36(String desc36) {
        this.desc36 = desc36;
    }

    public String getDesc37() {
        return desc37;
    }

    public void setDesc37(String desc37) {
        this.desc37 = desc37;
    }

    public String getDesc38() {
        return desc38;
    }

    public void setDesc38(String desc38) {
        this.desc38 = desc38;
    }

    public String getDesc39() {
        return desc39;
    }

    public void setDesc39(String desc39) {
        this.desc39 = desc39;
    }

    public String getDesc40() {
        return desc40;
    }

    public void setDesc40(String desc40) {
        this.desc40 = desc40;
    }

    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_detail.tel
     *
     * @param tel the value for shop_detail.tel
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_detail.address
     *
     * @return the value of shop_detail.address
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_detail.address
     *
     * @param address the value for shop_detail.address
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_detail.publish_start
     *
     * @return the value of shop_detail.publish_start
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public Date getPublishStart() {
        return publishStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_detail.publish_start
     *
     * @param publishStart the value for shop_detail.publish_start
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public void setPublishStart(Date publishStart) {
        this.publishStart = publishStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_detail.publish_end
     *
     * @return the value of shop_detail.publish_end
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public Date getPublishEnd() {
        return publishEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_detail.publish_end
     *
     * @param publishEnd the value for shop_detail.publish_end
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public void setPublishEnd(Date publishEnd) {
        this.publishEnd = publishEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_detail.create_datetime
     *
     * @return the value of shop_detail.create_datetime
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_detail.create_datetime
     *
     * @param createDatetime the value for shop_detail.create_datetime
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_detail.update_datetime
     *
     * @return the value of shop_detail.update_datetime
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_detail.update_datetime
     *
     * @param updateDatetime the value for shop_detail.update_datetime
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_detail.del_flg
     *
     * @return the value of shop_detail.del_flg
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_detail.del_flg
     *
     * @param delFlg the value for shop_detail.del_flg
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_detail.note
     *
     * @return the value of shop_detail.note
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_detail.note
     *
     * @param note the value for shop_detail.note
     *
     * @mbggenerated Mon Mar 12 10:31:54 CST 2018
     */
    public void setNote(String note) {
        this.note = note;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public Integer getShopType() {
        return shopType;
    }

    public void setShopType(Integer shopType) {
        this.shopType = shopType;
    }

    public String getNow5() {
        return now5;
    }

    public void setNow5(String now5) {
        this.now5 = now5;
    }

    public String getDesc41() {
        return desc41;
    }

    public void setDesc41(String desc41) {
        this.desc41 = desc41;
    }

    public String getDesc42() {
        return desc42;
    }

    public void setDesc42(String desc42) {
        this.desc42 = desc42;
    }

    public String getDesc43() {
        return desc43;
    }

    public void setDesc43(String desc43) {
        this.desc43 = desc43;
    }

}