package jp.co.vermore.entity;

import jp.co.vermore.common.mvc.BaseEntity;

public class SystemConf extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_conf.id
     *
     * @mbggenerated Thu Mar 29 16:16:52 JST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_conf.setting
     *
     * @mbggenerated Thu Mar 29 16:16:52 JST 2018
     */
    private Integer setting;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_conf.value
     *
     * @mbggenerated Thu Mar 29 16:16:52 JST 2018
     */
    private Integer value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_conf.id
     *
     * @return the value of system_conf.id
     *
     * @mbggenerated Thu Mar 29 16:16:52 JST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_conf.id
     *
     * @param id the value for system_conf.id
     *
     * @mbggenerated Thu Mar 29 16:16:52 JST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_conf.setting
     *
     * @return the value of system_conf.setting
     *
     * @mbggenerated Thu Mar 29 16:16:52 JST 2018
     */
    public Integer getSetting() {
        return setting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_conf.setting
     *
     * @param setting the value for system_conf.setting
     *
     * @mbggenerated Thu Mar 29 16:16:52 JST 2018
     */
    public void setSetting(Integer setting) {
        this.setting = setting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_conf.value
     *
     * @return the value of system_conf.value
     *
     * @mbggenerated Thu Mar 29 16:16:52 JST 2018
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_conf.value
     *
     * @param value the value for system_conf.value
     *
     * @mbggenerated Thu Mar 29 16:16:52 JST 2018
     */
    public void setValue(Integer value) {
        this.value = value;
    }
}