package jp.co.vermore.entity;

import jp.co.vermore.common.mvc.BaseEntity;

import java.util.Date;

public class Tv extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv.id
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv.uuid
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv.title
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv.office
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    private String office;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv.url
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv.tv_type
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    private Byte tvType;

    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv.sort_score
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    private Integer sortScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv.date
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv.publish_start
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    private Date publishStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv.publish_end
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    private Date publishEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv.category
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    private Byte category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv.create_datetime
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv.update_datetime
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv.del_flg
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    private Boolean delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv.note
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv.id
     *
     * @return the value of tv.id
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    public Long getId() {
        return id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv.uuid
     *
     * @return the value of tv.uuid
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv.uuid
     *
     * @param uuid the value for tv.uuid
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv.title
     *
     * @return the value of tv.title
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv.title
     *
     * @param title the value for tv.title
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv.office
     *
     * @return the value of tv.office
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    public String getOffice() {
        return office;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv.office
     *
     * @param office the value for tv.office
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    public void setOffice(String office) {
        this.office = office;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv.url
     *
     * @return the value of tv.url
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv.url
     *
     * @param url the value for tv.url
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv.tv_type
     *
     * @return the value of tv.tv_type
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    public Byte getTvType() {
        return tvType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv.tv_type
     *
     * @param tvType the value for tv.tv_type
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    public void setTvType(Byte tvType) {
        this.tvType = tvType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv.sort_score
     *
     * @return the value of tv.sort_score
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    public Integer getSortScore() {
        return sortScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv.sort_score
     *
     * @param sortScore the value for tv.sort_score
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    public void setSortScore(Integer sortScore) {
        this.sortScore = sortScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv.date
     *
     * @return the value of tv.date
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv.date
     *
     * @param date the value for tv.date
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv.publish_start
     *
     * @return the value of tv.publish_start
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    public Date getPublishStart() {
        return publishStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv.publish_start
     *
     * @param publishStart the value for tv.publish_start
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    public void setPublishStart(Date publishStart) {
        this.publishStart = publishStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv.publish_end
     *
     * @return the value of tv.publish_end
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    public Date getPublishEnd() {
        return publishEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv.publish_end
     *
     * @param publishEnd the value for tv.publish_end
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    public void setPublishEnd(Date publishEnd) {
        this.publishEnd = publishEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv.category
     *
     * @return the value of tv.category
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    public Byte getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv.category
     *
     * @param category the value for tv.category
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    public void setCategory(Byte category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv.create_datetime
     *
     * @return the value of tv.create_datetime
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv.create_datetime
     *
     * @param createDatetime the value for tv.create_datetime
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv.update_datetime
     *
     * @return the value of tv.update_datetime
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv.update_datetime
     *
     * @param updateDatetime the value for tv.update_datetime
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv.del_flg
     *
     * @return the value of tv.del_flg
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv.del_flg
     *
     * @param delFlg the value for tv.del_flg
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv.note
     *
     * @return the value of tv.note
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv.note
     *
     * @param note the value for tv.note
     *
     * @mbggenerated Fri Jun 08 15:07:59 CST 2018
     */
    public void setNote(String note) {
        this.note = note;
    }

    public Byte getType() {
        return type;
    }

    public void setType(Byte type) {
        this.type = type;
    }
}