package jp.co.vermore.entity;

import jp.co.vermore.common.mvc.BaseEntity;

import java.util.Date;

public class TvDetail extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_detail.id
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_detail.tv_id
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    private Long tvId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_detail.title
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_detail.detail
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_detail.type
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_detail.date
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_detail.publish_start
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    private Date publishStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_detail.publish_end
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    private Date publishEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_detail.category
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    private Byte category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_detail.create_datetime
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_detail.update_datetime
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_detail.del_flg
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    private Boolean delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_detail.note
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_detail.id
     *
     * @return the value of tv_detail.id
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    @Override
    public Long getId() {
        return id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public Long getTvId() {
        return tvId;
    }

    public void setTvId(Long tvId) {
        this.tvId = tvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_detail.title
     *
     * @return the value of tv_detail.title
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_detail.title
     *
     * @param title the value for tv_detail.title
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_detail.detail
     *
     * @return the value of tv_detail.detail
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_detail.detail
     *
     * @param detail the value for tv_detail.detail
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_detail.type
     *
     * @return the value of tv_detail.type
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_detail.type
     *
     * @param type the value for tv_detail.type
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_detail.date
     *
     * @return the value of tv_detail.date
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_detail.date
     *
     * @param date the value for tv_detail.date
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_detail.publish_start
     *
     * @return the value of tv_detail.publish_start
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    public Date getPublishStart() {
        return publishStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_detail.publish_start
     *
     * @param publishStart the value for tv_detail.publish_start
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    public void setPublishStart(Date publishStart) {
        this.publishStart = publishStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_detail.publish_end
     *
     * @return the value of tv_detail.publish_end
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    public Date getPublishEnd() {
        return publishEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_detail.publish_end
     *
     * @param publishEnd the value for tv_detail.publish_end
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    public void setPublishEnd(Date publishEnd) {
        this.publishEnd = publishEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_detail.category
     *
     * @return the value of tv_detail.category
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    public Byte getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_detail.category
     *
     * @param category the value for tv_detail.category
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    public void setCategory(Byte category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_detail.create_datetime
     *
     * @return the value of tv_detail.create_datetime
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_detail.create_datetime
     *
     * @param createDatetime the value for tv_detail.create_datetime
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_detail.update_datetime
     *
     * @return the value of tv_detail.update_datetime
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_detail.update_datetime
     *
     * @param updateDatetime the value for tv_detail.update_datetime
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_detail.del_flg
     *
     * @return the value of tv_detail.del_flg
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_detail.del_flg
     *
     * @param delFlg the value for tv_detail.del_flg
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_detail.note
     *
     * @return the value of tv_detail.note
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_detail.note
     *
     * @param note the value for tv_detail.note
     *
     * @mbggenerated Fri Jun 08 16:51:57 CST 2018
     */
    public void setNote(String note) {
        this.note = note;
    }
}