package jp.co.vermore.entity;

import jp.co.vermore.common.mvc.BaseEntity;

import java.util.Date;

public class Withdraw extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw.id
     *
     * @mbggenerated Mon May 21 23:36:45 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw.user_id
     *
     * @mbggenerated Mon May 21 23:36:45 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw.reason
     *
     * @mbggenerated Mon May 21 23:36:45 CST 2018
     */
    private Byte reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw.detail
     *
     * @mbggenerated Mon May 21 23:36:45 CST 2018
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw.create_datetime
     *
     * @mbggenerated Mon May 21 23:36:45 CST 2018
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw.update_datetime
     *
     * @mbggenerated Mon May 21 23:36:45 CST 2018
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw.del_flg
     *
     * @mbggenerated Mon May 21 23:36:45 CST 2018
     */
    private Boolean delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw.note
     *
     * @mbggenerated Mon May 21 23:36:45 CST 2018
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw.id
     *
     * @return the value of withdraw.id
     *
     * @mbggenerated Mon May 21 23:36:45 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw.id
     *
     * @param id the value for withdraw.id
     *
     * @mbggenerated Mon May 21 23:36:45 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw.user_id
     *
     * @return the value of withdraw.user_id
     *
     * @mbggenerated Mon May 21 23:36:45 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw.user_id
     *
     * @param userId the value for withdraw.user_id
     *
     * @mbggenerated Mon May 21 23:36:45 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw.reason
     *
     * @return the value of withdraw.reason
     *
     * @mbggenerated Mon May 21 23:36:45 CST 2018
     */
    public Byte getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw.reason
     *
     * @param reason the value for withdraw.reason
     *
     * @mbggenerated Mon May 21 23:36:45 CST 2018
     */
    public void setReason(Byte reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw.detail
     *
     * @return the value of withdraw.detail
     *
     * @mbggenerated Mon May 21 23:36:45 CST 2018
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw.detail
     *
     * @param detail the value for withdraw.detail
     *
     * @mbggenerated Mon May 21 23:36:45 CST 2018
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw.create_datetime
     *
     * @return the value of withdraw.create_datetime
     *
     * @mbggenerated Mon May 21 23:36:45 CST 2018
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw.create_datetime
     *
     * @param createDatetime the value for withdraw.create_datetime
     *
     * @mbggenerated Mon May 21 23:36:45 CST 2018
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw.update_datetime
     *
     * @return the value of withdraw.update_datetime
     *
     * @mbggenerated Mon May 21 23:36:45 CST 2018
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw.update_datetime
     *
     * @param updateDatetime the value for withdraw.update_datetime
     *
     * @mbggenerated Mon May 21 23:36:45 CST 2018
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw.del_flg
     *
     * @return the value of withdraw.del_flg
     *
     * @mbggenerated Mon May 21 23:36:45 CST 2018
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw.del_flg
     *
     * @param delFlg the value for withdraw.del_flg
     *
     * @mbggenerated Mon May 21 23:36:45 CST 2018
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw.note
     *
     * @return the value of withdraw.note
     *
     * @mbggenerated Mon May 21 23:36:45 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw.note
     *
     * @param note the value for withdraw.note
     *
     * @mbggenerated Mon May 21 23:36:45 CST 2018
     */
    public void setNote(String note) {
        this.note = note;
    }
}